(function(g){var window=this;'use strict';var pU=function(Y){Y.publish("cardstatechange",Y.xo()&&Y.ol()?1:0)},ch=function(Y,e){var K=g.zP(e),x=K?e:arguments;
for(K=K?0:1;K<x.length;K++){if(Y==null)return;Y=Y[x[K]]}return Y},cBL=function(Y){var e=g.tI(Y);
Y=g.Kh(Y);return new g.SG(e.x,e.y,Y.width,Y.height)},V4L=function(Y,e,K){var x=x===void 0?{}:x;
var z;return z=g.Bp(Y,e,function(){g.L7(z);K.apply(Y,arguments)},x)},gH=function(Y){Y=g.TP(Y);
delete VV[Y];g.kM(VV)&&CU&&CU.stop()},gLz=function(){CU||(CU=new g.S2(function(){C$1()},20));
var Y=CU;Y.isActive()||Y.start()},C$1=function(){var Y=g.kx();
g.t0(VV,function(e){ABP(e,Y)});
g.kM(VV)||gLz()},AO=function(Y,e,K,x){g.zX.call(this);
if(!Array.isArray(Y)||!Array.isArray(e))throw Error("Start and end parameters must be arrays");if(Y.length!=e.length)throw Error("Start and end points must be the same length");this.L=Y;this.T=e;this.duration=K;this.B=x;this.coords=[];this.progress=this.U=0;this.Y=null},ABP=function(Y,e){e<Y.startTime&&(Y.endTime=e+Y.endTime-Y.startTime,Y.startTime=e);
Y.progress=(e-Y.startTime)/(Y.endTime-Y.startTime);Y.progress>1&&(Y.progress=1);Y.U=1E3/(e-Y.Y);Y.Y=e;vLZ(Y,Y.progress);Y.progress==1?(Y.K=0,gH(Y),Y.onFinish(),Y.zk()):Y.isPlaying()&&Y.JA()},vLZ=function(Y,e){typeof Y.B==="function"&&(e=Y.B(e));
Y.coords=Array(Y.L.length);for(var K=0;K<Y.L.length;K++)Y.coords[K]=(Y.T[K]-Y.L[K])*e+Y.L[K]},rBd=function(Y,e){g.lz.call(this,Y);
this.coords=e.coords;this.x=e.coords[0];this.y=e.coords[1];this.z=e.coords[2];this.duration=e.duration;this.progress=e.progress;this.fps=e.U;this.state=e.K},vh=function(Y,e,K,x,z){AO.call(this,e,K,x,z);
this.element=Y},jp0=function(Y,e,K,x,z){if(e.length!=2||K.length!=2)throw Error("Start and end points must be 2D");
vh.call(this,Y,e,K,x,z)},i9M=function(Y){return Math.pow(Y,3)},JBa=function(Y){return 3*Y*Y-2*Y*Y*Y},SHL=function(Y){g.J.call(this);
this.L=Y||window;this.K=[]},rH=function(Y){return Y.baseUrl||null},jN=function(Y,e){return g.N4(g.fh(Y,e),function(K){return!!K})},W76=function(Y,e,K){function x(GM){var TM=GM.hovercardButton;
if(!TM)return null;TM=TM.subscribeButtonRenderer;if(!TM)return null;var F9=O(TM.unsubscribedButtonText),ec=O(TM.subscribedButtonText);if(TM.subscribed){var NP=O(TM.subscriberCountWithUnsubscribeText);var y$=O(TM.subscriberCountText)}else NP=O(TM.subscriberCountText),y$=O(TM.subscriberCountWithSubscribeText);var e6=null;if(GM.signinEndpoint){e6=ch(GM,"signinEndpoint","webNavigationEndpointData","url");if(!e6){var fa,FA;e6=(FA=g.l((fa=TM.signInEndpoint)==null?void 0:fa.commandMetadata,g.a_))==null?
void 0:FA.url}if(!e6)return null}return F9&&(ec||e6)?{subscribed:TM.subscribed,subscribeText:F9,subscribeCount:NP,unsubscribeText:ec,unsubscribeCount:y$,enabled:TM.enabled,signinUrl:e6,classic:GM.useClassicSubscribeButton}:null}
function z(GM){if(GM){var TM=[],F9=GM.videoId;F9&&TM.push("v="+F9);(F9=GM.playlistId)&&TM.push("list="+F9);(GM=GM.startTimeSeconds)&&TM.push("t="+GM);return"/watch?"+TM.join("&")}}
function O(GM){if(!GM)return null;var TM=GM.simpleText;return TM?TM:GM.runs?g.fh(GM.runs,function(F9){return F9.text}).join(""):null}
e=e.endscreenElementRenderer;if(!e)return null;var T=e.style,E=e.endpoint||{},u=null,b=null,k=!1,G=null,B=null,L=null,f=null,U=!1,h=null,Z=null,N=null,V=null,r=null,H=null;if(T==="VIDEO")g.l(E,g.p4)?u=g.l(E,g.p4).url:(H=g.l(E,g.QW),u=z(H)),b=!1,G=Y,e.thumbnailOverlays?(k=e.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,B=O(k.text),k=k.style==="LIVE"):B=O(e.videoDuration);else if(T==="PLAYLIST")g.l(E,g.p4)?u=g.l(E,g.p4).url:(H=g.l(E,g.QW),u=z(H)),b=!1,G=Y,L=O(e.playlistLength);else if(T===
"CHANNEL"){if(U=ch(E,"browseEndpoint","browseId"))f=U,u="/channel/"+f;b=!1;G="new";(U=!!e.isSubscribe)?h=x(e):Z=O(e.subscribersText)}else T==="WEBSITE"?((N=ch(E,"urlEndpoint","url"))&&(u=N),b=!0,G="new",N=e.icon.thumbnails[0].url):T==="CREATOR_MERCHANDISE"&&(e.productPrice&&(V=O(e.productPrice)),e.additionalFeesText&&(r=O(e.additionalFeesText)),(b=ch(E,"urlEndpoint","url"))&&(u=b),b=!0,G="new");Y=ch(e,"title","accessibility","accessibilityData","label");var I=e.endpoint?e.endpoint.clickTrackingParams:
null,w="";if(e.metadata){var $O=O(e.metadata);$O&&(w=$O)}return{id:"element-"+K,type:T,title:O(e.title),metadata:w,callToAction:O(e.callToAction),J0:e.image,iconUrl:N,left:Number(e.left),width:Number(e.width),top:Number(e.top),aspectRatio:Number(e.aspectRatio),startMs:Math.floor(Number(e.startMs)),endMs:Math.floor(Number(e.endMs)),videoDuration:B,zc:k,playlistLength:L,channelId:f,subscribeButton:h,subscribersText:Z,isSubscribe:U,targetUrl:u||null,sA:b,sessionData:I?{itct:I}:null,EpZ:G,Ke:Y?Y:null,
isPlaceholder:e.isPlaceholder,impressionUrls:jN(e.impressionUrls||[],rH),Hs:jN(e.hovercardShowUrls||[],rH),clickUrls:jN(E.loggingUrls||[],rH),visualElement:g.od(e.trackingParams),productPrice:V,additionalFeesText:r,watchEndpoint:H||null}},H9n=function(Y,e){var K={startMs:Math.floor(Number(Y.startMs)),
impressionUrls:jN(Y.impressionUrls||[],rH),elements:jN(Y.elements||[],function(x,z){return W76(e,x,z)})};
Y.trackingParams&&(K.visualElement=g.od(Y.trackingParams));return K},lpx=function(Y){g.Ms.call(this,Y);
this.Y=this.endscreen=null;this.L={};this.U={};this.B=this.X=null;this.S=[];this.K=null;this.nF=!0;this.T=0;Y=Y.D();this.C=g.Tr(Y)||g.Ev(Y);this.events=new g.US(this);g.S(this,this.events);this.events.J(this.player,g.d2("creatorendscreen"),this.onCueRangeEnter);this.events.J(this.player,g.qt("creatorendscreen"),this.onCueRangeExit);this.events.J(this.player,"resize",this.DK);this.events.J(window,"focus",this.ETq);this.load();var e=g.ob("STYLE");(g.zR("HEAD")[0]||document.body).appendChild(e);this.addOnDisposeCallback(function(){g.Rb(e)});
e.sheet&&(e.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),e.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},dlz=function(Y){return Y.player.getVideoData().Fq?"current":Y.C?"new":"current"},iw=function(Y){return Y.player.D().playerStyle==="creator-endscreen-editor"},qHq=function(Y){var e=Y.player.getVideoData(),K=e.videoId;
Y.Y&&Y.Y.abort();K={method:"POST",onFinish:function(z){var O=Y.Y=null;z.status===200&&(z=z.responseText,z.substring(0,3)===")]}"&&(z=z.substring(3),O=JSON.parse(z),O=H9n(O,dlz(Y))));JO(Y,O)},
urlParams:{v:K},withCredentials:!0};Y.C&&(K.urlParams.ptype="embedded");var x=e.R4;x&&(K.postParams={ad_tracking:x});if(e=g.d6o(e))if(e=g.On(e),e=g.sn(e))Y.Y=g.RE(e,K)},JO=function(Y,e,K){K=K===void 0?!0:K;
Y.player.l1("creatorendscreen");Y.X&&(Y.X.dispose(),Y.X=null,Y.B.dispose(),Y.B=null);for(var x=g.a(Object.values(Y.L)),z=x.next();!z.done;z=x.next())z.value.dispose();Y.L={};Y.U={};Y.S.length>0&&(Y.S.forEach(function(E){E.dispose()}),Y.S.length=0);
Y.K&&(g.Kw(Y.K,"ytp-ce-element-show"),Y.K.setAttribute("aria-hidden","true"));Y.T=0;if((Y.endscreen=e)&&e.elements){K&&nL0(Y);K=[];x=new g.HU(e.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});K.push(x);Y.player.D().L||(Y.X=new g.d({N:"div",j:"ytp-ce-shadow"}),g.Yw(Y.player,Y.X.element,4),Y.B=new g.wy(Y.X,200));for(x=0;x<e.elements.length;++x){z=e.elements[x];var O=wIq(Y,z);if(O){Y.L[z.id]=O;Y.U[z.id]=z;g.Yw(Y.player,O.element,4);var T=new g.HU(z.startMs,z.endMs,{id:"ytp-ce-element-"+
z.id,namespace:"creatorendscreen"});K.push(T);yBU(Y,O,z)}else g.P1(new g.iD("buildEndscreenElement null",z))}Y.player.B_(K);Y.DK()}},nL0=function(Y){var e=g.B1(),K=g.Ld();
K&&e&&Y.endscreen.visualElement&&g.lN(g.jX)(void 0,K,e,Y.endscreen.visualElement)},wIq=function(Y,e){var K=null;
switch(e.type){case "VIDEO":Y={N:"div",v2:["ytp-ce-element","ytp-ce-video"],V:{tabindex:"0","aria-label":e.Ke||"","aria-hidden":"true"},G:[{N:"div",j:"ytp-ce-element-shadow"},{N:"div",j:"ytp-ce-covering-image",V:SN(e)},{N:"div",j:"ytp-ce-covering-shadow-top"},{N:"a",j:"ytp-ce-covering-overlay",V:{href:Wh(Y,e.targetUrl),tabindex:"-1"},G:[{N:"div",v2:["ytp-ce-video-title","ytp-webkit-ellipsis"],V:{dir:g.E$(e.title||"")},Qq:e.title},{N:"div",j:e.zc?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
Qq:e.videoDuration||void 0}]}]};K=new g.d(Y);break;case "PLAYLIST":Y={N:"div",v2:["ytp-ce-element","ytp-ce-playlist"],V:{tabindex:"0","aria-label":e.Ke||"","aria-hidden":"true"},G:[{N:"div",j:"ytp-ce-element-shadow"},{N:"div",j:"ytp-ce-covering-image",V:SN(e)},{N:"div",j:"ytp-ce-covering-shadow-top"},{N:"a",j:"ytp-ce-covering-overlay",V:{href:Wh(Y,e.targetUrl),tabindex:"-1"},G:[{N:"div",v2:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],V:{dir:g.E$(e.title||"")},Qq:e.title},{N:"div",j:"ytp-ce-playlist-count",
G:[{N:"div",j:"ytp-ce-playlist-icon"},{N:"div",j:"ytp-ce-playlist-count-text",Qq:e.playlistLength||void 0}]}]}]};K=new g.d(Y);break;case "CHANNEL":K={N:"div",v2:["ytp-ce-element","ytp-ce-channel",e.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],V:{tabindex:"0","aria-label":e.Ke||"","aria-hidden":"true"},G:[{N:"div",j:"ytp-ce-element-shadow"},{N:"div",j:"ytp-ce-expanding-overlay",G:[{N:"div",j:"ytp-ce-expanding-overlay-hider"},{N:"div",j:"ytp-ce-expanding-overlay-background"},{N:"div",j:"ytp-ce-expanding-overlay-content",
G:[{N:"div",j:"ytp-ce-expanding-overlay-body",G:[{N:"div",j:"ytp-ce-expanding-overlay-body-padding",G:[{N:"a",v2:["ytp-ce-channel-title","ytp-ce-link"],V:{href:Wh(Y,e.targetUrl),target:"_blank",tabindex:"-1",dir:g.E$(e.title||"")},Qq:e.title},e.subscribeButton?{N:"div",j:"ytp-ce-subscribe-container",G:[{N:"div",j:"ytp-ce-channel-subscribe"}]}:"",e.subscribersText?{N:"div",j:"ytp-ce-channel-subscribers-text",Qq:e.subscribersText}:"",e.metadata?{N:"div",v2:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],Qq:e.metadata}:""]}]}]}]},{N:"div",j:"ytp-ce-expanding-image",V:SN(e)}]};K=new g.d(K);var x=g.Oj(document,"div","ytp-ce-channel-subscribe",K.element)[0];if(e.subscribeButton&&e.channelId){g.YI(x,"ytp-ce-subscribe-button");if(Y.player.D().L){var z=null;var O=e.sessionData.itct}else z="endscreen",O=null;z=new g.$4(e.subscribeButton.subscribeText,e.subscribeButton.subscribeCount,e.subscribeButton.unsubscribeText,e.subscribeButton.unsubscribeCount,!!e.subscribeButton.enabled,!!e.subscribeButton.classic,
e.channelId,!!e.subscribeButton.subscribed,z,O,Y.player,!1);x.appendChild(z.element);Y.S.push(z)}break;case "WEBSITE":Y={N:"div",v2:["ytp-ce-element","ytp-ce-website"],V:{tabindex:"0","aria-label":e.Ke||"","aria-hidden":"true"},G:[{N:"div",j:"ytp-ce-element-shadow"},{N:"div",j:"ytp-ce-expanding-overlay",G:[{N:"div",j:"ytp-ce-expanding-overlay-hider"},{N:"div",j:"ytp-ce-expanding-overlay-background"},{N:"div",j:"ytp-ce-expanding-overlay-content",G:[{N:"div",j:"ytp-ce-expanding-overlay-body",G:[{N:"div",
j:"ytp-ce-expanding-overlay-body-padding",G:[{N:"div",j:"ytp-ce-website-title",V:{dir:g.E$(e.title||"")},Qq:e.title},{N:"div",j:"ytp-ce-website-metadata",Qq:e.metadata},{N:"a",v2:["ytp-ce-website-goto","ytp-ce-link"],V:{href:Wh(Y,e.targetUrl),target:"_blank",tabindex:"-1"},Qq:e.callToAction}]}]}]}]},{N:"div",j:"ytp-ce-expanding-image",V:SN(e)},{N:"div",j:"ytp-ce-expanding-icon",V:Ipn(e.iconUrl)}]};K=new g.d(Y);break;case "CREATOR_MERCHANDISE":K="",e.productPrice&&(K={N:"div",j:"ytp-ce-merchandise-price-container",
G:[{N:"div",j:"ytp-ce-merchandise-price",Qq:e.productPrice}]},e.additionalFeesText&&K.G.push({N:"div",j:"ytp-ce-merchandise-additional-fees",Qq:e.additionalFeesText})),Y={N:"div",v2:["ytp-ce-element","ytp-ce-merchandise"],V:{tabindex:"0","aria-label":e.Ke||"","aria-hidden":"true"},G:[{N:"div",j:"ytp-ce-element-shadow"},{N:"div",j:"ytp-ce-expanding-overlay",G:[{N:"div",j:"ytp-ce-expanding-overlay-hider"},{N:"div",j:"ytp-ce-expanding-overlay-background"},{N:"div",j:"ytp-ce-expanding-overlay-content",
G:[{N:"div",j:"ytp-ce-expanding-overlay-body",G:[{N:"div",j:"ytp-ce-expanding-overlay-body-padding",G:[{N:"div",j:"ytp-ce-merchandise-title",V:{dir:g.E$(e.title||"")},Qq:e.title},K,{N:"div",j:"ytp-ce-merchandise-metadata",Qq:e.metadata},{N:"a",v2:["ytp-ce-merchandise-goto","ytp-ce-link"],V:{href:Wh(Y,e.targetUrl),target:"_blank",tabindex:"-1"},Qq:e.callToAction}]}]}]}]},{N:"div",j:"ytp-ce-expanding-image",V:SN(e)},{N:"div",j:"ytp-ce-merchandise-invideo-cta-container",G:[{N:"div",j:"ytp-ce-merchandise-invideo-cta",
Qq:e.callToAction||void 0}]}]},K=new g.d(Y)}e.isPlaceholder&&g.YI(K.element,"ytp-ce-placeholder");return K},SN=function(Y){if(Y.J0)var e=Y.J0.thumbnails;
return Ipn(e?e[e.length-1].url:null)},Ipn=function(Y){return Y?{style:"background-image: url("+Y+")"}:{}},yBU=function(Y,e,K){function x(u){u&&(e.listen("blur",function(){u.style.display!="none"&&Y.nF&&u.focus()}),e.J(u,"focus",O),e.J(u,"blur",T))}
function z(u){Y.T+=u;Y.T>0?(g.YI(e.element,"ytp-ce-force-expand"),Hh(Y,K.id,!0)):(g.Kw(e.element,"ytp-ce-force-expand"),g.Kw(e.element,"ytp-ce-element-hover"),Hh(Y,K.id,!1))}
function O(){z(1)}
function T(){z(-1)}
e.listen("mouseenter",function(){Dl6(Y,e,K)});
e.listen("mouseleave",function(){t47(Y,e,K)});
Y.player.D().L||e.listen("click",function(){g.YI(e.element,"ytp-ce-element-hover")});
e.listen("click",function(u){YOM(Y,K,u)});
e.listen("keypress",function(u){YOM(Y,K,u)});
e.listen("focus",function(){Dl6(Y,e,K)});
e.listen("blur",function(){t47(Y,e,K)});
e.listen("touchstart",function(){Dl6(Y,e,K)});
var E=g.TR("ytp-ce-expanding-overlay-hider",e.element);E&&e.J(E,"touchstart",function(u){u.stopPropagation();g.Kw(e.element,"ytp-ce-element-hover");g.Kw(e.element,"ytp-ce-force-expand")});
e.listen("keydown",function(u){Y.nF=u.keyCode===9&&!u.shiftKey});
x(g.TR("ytp-sb-subscribe",e.element));x(g.TR("ytp-sb-unsubscribe",e.element));e.listen("focus",O);e.listen("blur",T)},YOM=function(Y,e,K){if(e.targetUrl&&(!K||K.type!=="keypress"||K.keyCode===13)){for(var x=K.target;x&&!g.tA(x,"ytp-ce-element");){g.tA(x,"subscribe-label")&&e9a(Y,e);
if(g.tA(x,"ytp-ce-channel-subscribe"))return;x=x.parentElement||null}if(!x||g.tA(x,"ytp-ce-element-hover")){K.preventDefault();K.stopPropagation();if(x=Y.L[e.id])t47(Y,x,e),x.element.blur();if(K.ctrlKey||K.metaKey||e.EpZ==="new")e9a(Y,e),Y.player.sendVideoStatsEngageEvent(17,void 0),Y.player.pauseVideo(),K=g.On(Wh(Y,e.targetUrl)),K=g.sn(K),g.jR(K,void 0,e.sessionData);else{var z=g.Uv(Y.player.D())||Y.player.getVideoData().Fq,O=function(){var T=Wh(Y,e.targetUrl),E=e.sessionData,u=e.watchEndpoint,b=
g.Dk(T);z&&b&&(b.v||b.list)?Y.player.Gw(b.v,E,b.list,!1,void 0,u||void 0):g.rf(T,E)};
e9a(Y,e,function(){Y.player.sendVideoStatsEngageEvent(17,O)})}}}},Wh=function(Y,e){Y=Y.player.D();
if(e){if(e.startsWith("//"))return Y.protocol+":"+e;if(e.startsWith("/"))return g.cm(Y)+e}else return"";return e},Dl6=function(Y,e,K){g.tA(e.element,"ytp-ce-element-hover")||(K.type==="VIDEO"||K.type==="PLAYLIST"?g.YI(e.element,"ytp-ce-element-hover"):Y.player.D().L?(new g.S2(function(){g.YI(e.element,"ytp-ce-element-hover")},200)).start():g.YI(e.element,"ytp-ce-element-hover"),lw(Y,K.Hs),Hh(Y,K.id,!0))},t47=function(Y,e,K){g.Kw(e.element,"ytp-ce-element-hover");
g.Kw(e.element,"ytp-ce-force-expand");Hh(Y,K.id,!1)},Hh=function(Y,e,K){Y.X&&(K?Y.B.show():Y.B.hide());
for(var x=g.a(Object.keys(Y.L)),z=x.next();!z.done;z=x.next())z=z.value,z!==e&&g.s$(Y.L[z].element,"ytp-ce-element-shadow-show",K)},lw=function(Y,e,K){function x(){O||(z++,z===e.length&&(T.stop(),K&&K()))}
if(!e||e.length===0||iw(Y))K&&K();else{e=Kw1(Y,e);var z=0,O=!1,T=new g.S2(function(){O=!0;K&&K()},1E3,Y);
T.start();for(Y=0;Y<e.length;Y++)g.pG(e[Y],x)}},e9a=function(Y,e,K){lw(Y,e.clickUrls,K);
(Y=g.Ld())&&e.sA&&g.yd(Y,e.visualElement)},Kw1=function(Y,e){var K=Y.player.getVideoData().clientPlaybackNonce;
Y=Y.player.getCurrentTime().toFixed(2);K={CPN:K,AD_CPN:K,MT:Y};Y=[];for(var x=0;x<e.length;x++)Y.push(xa0(e[x],K));return Y},xa0=function(Y,e){return Y.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(K){var x=unescape(K);
x=x.substring(1,x.length-1);return e[x]?escape(e[x]):K})},sJA=function(Y){return typeof Y==="string"?Y:""},dH=function(Y,e,K){for(var x in e)if(e[x]===Y)return Y;
return K},z9A=function(Y,e,K,x){this.value=Y;
this.target=e;this.showLinkIcon=K;this.K=x},qR=function(Y){return Y.value?Y.value:null},nU=function(Y){if(!Y)return null;
var e=g.On(sJA(Y.value));e=g.sn(e);if(!e)return null;var K=dH(Y.target,$ad,"current");if(K==null)Y=null;else{var x=Y.show_link_icon;Y=new z9A(e,K,x==="true"||x==="false"?x==="true":!0,Y.pause_on_navigation!=null?Y.pause_on_navigation:!0)}return Y},OTP=function(Y,e,K){this.type=Y;
this.trigger=e;this.url=K},ETU=function(Y){if(!Y)return null;
var e=dH(Y.type,TU6),K=dH(Y.trigger,Fw6);Y=Y.url;Y=Array.isArray(Y)&&Y.length?Y[0]:Y;Y=nU(Y?Y:null);return e?new OTP(e,K,Y):null},uiU=function(Y,e,K,x,z){this.id=Y;
this.type=e;this.style=K;this.data=z;this.action=x||[]},bT1=function(Y,e){return g.mZ(Y.action,e)},ka0=function(Y,e){this.context=Y;
this.K=e},oTU=function(Y){return Y.customMessage?wH("div","iv-card-message",Y.customMessage):""},yV=function(Y,e){Y="background-image: url("+Y+");";
var K=[];e&&K.push(e);return{N:"div",j:"iv-card-image",V:{style:Y},G:K}},Ga6=function(Y){if(!Y.metaInfo||Y.metaInfo.length===0)return"";
var e=[];Y=g.a(Y.metaInfo);for(var K=Y.next();!K.done;K=Y.next())e.push(wH("li","",K.value));return{N:"ul",j:"iv-card-meta-info",G:e}},wH=function(Y,e,K){e?typeof e==="string"?e={"class":e}:Array.isArray(e)&&(e={"class":e.join(" ")}):e={};
e.dir=g.E$(K);return{N:Y,V:e,Qq:K}},BUd=function(Y){if(!Y.customMessage)return"";
var e=["iv-card-action","iv-card-primary-link"],K={};Y.vE&&(e.push("iv-card-action-icon"),K.style="background-image: url("+Y.vE+");");K.dir=g.E$(Y.customMessage);var x=[{N:"span",Qq:Y.customMessage}];Y.showLinkIcon&&(x.push("\u00a0"),x.push({N:"span",j:"iv-card-link-icon"}));return{N:"div",v2:e,V:K,G:x}},I2=function(Y,e,K,x){if(x){e=g.a(e);
for(var z=e.next();!z.done;z=e.next())Y.K(z.value,x,K.id,K.sessionData,K.hF.click,5)}},Lwz=function(Y,e){this.merchant=Y;
this.price=e},fnU=function(Y){var e;
(e=Y)&&!(e=Y.length>1?Y.charAt(0)==="/"&&Y.charAt(1)!=="/":Y==="/")&&(e=Y.replace(/^(https?:)?\/\//,"").split("/",1),e=!e||e.length<1||!e[0]?[]:e[0].toLowerCase().split(".").reverse(),e=e[0]==="com"&&e[1]==="youtube"||e[0]==="be"&&e[1]==="youtu");return e?Y.indexOf("/redirect?")===-1:!1},R9a=function(Y,e){return e?e:fnU(Y)?"current":"new"},Db=function(Y,e){g.J.call(this);
var K=this;this.element=Y;this.context=e;this.CF=!1;this.Sd=new Map;this.Vq=new Map;this.context.W.addEventListener(g.d2("annotations_module"),function(x){(x=K.Sd.get(x))&&x.apply(K)});
this.context.W.addEventListener(g.qt("annotations_module"),function(x){(x=K.Vq.get(x))&&x.apply(K)})},tO=function(Y,e,K,x,z,O,T){Y.context.K.listen(e,"click",function(E){Y.rF(K,x,z,O||[],T||0,E)});
Y.context.K.listen(e,"touchstart",function(){Y.CF=!1});
Y.context.K.listen(e,"touchmove",function(){Y.CF=!0})},ma6=function(Y){var e;
return((e=g.l(Y,g.p4))==null?0:e.url)?g.l(Y,g.p4).url:(Y=g.l(Y,g.QW))&&Y.videoId?(e="/watch?v="+Y.videoId,Y.playlistId&&(e+="&list="+Y.playlistId),Y.index&&(e+="&index="+Y.index),Y.startTimeSeconds&&(e+="&t="+Y.startTimeSeconds),e):null},YJ=function(Y,e,K){return{mJ:(Y.impressionLoggingUrlsV2s||[]).map(function(x){return x.baseUrl||""}),
click:(K.loggingUrls||[]).map(function(x){return x.baseUrl||""}),
close:(e.dismissLoggingUrlsV2s||[]).map(function(x){return x.baseUrl||""}),
qq:(e.impressionLoggingUrlsV2s||[]).map(function(x){return x.baseUrl||""}),
LH:(e.clickLoggingUrlsV2s||[]).map(function(x){return x.baseUrl||""})}},XG6=function(Y,e,K){Db.call(this,e,K);
var x=this;this.W=Y;this.eventId=null;this.Iq=this.Yq=this.hR=this.X=this.isInitialized=!1;this.cards=[];this.bJ=this.B=this.fF=this.U=this.g7=this.K=null;this.nF=[];this.xq=this.S=this.ud=this.X6=null;this.T=0;this.pF=new g.S2(function(){},K.ai.Cz?4E3:3E3);
g.S(this,this.pF);this.uJ=new g.S2(function(){});
g.S(this,this.uJ);this.LF=new ka0(K,function(z,O,T,E,u,b){tO(x,z,O,T,E,u,b)});
this.C=new g.d({N:"div",j:"iv-drawer",V:{id:"iv-drawer"},G:[{N:"div",j:"iv-drawer-header",V:{"aria-role":"heading"},G:[{N:"span",j:"iv-drawer-header-text"},{N:"button",v2:["iv-drawer-close-button","ytp-button"],V:{"aria-label":"\uce74\ub4dc \uc228\uae30\uae30",tabindex:"0"}}]},{N:"div",j:"iv-drawer-content"}]});g.S(this,this.C);this.Y=this.C.element;this.TZ=new g.wy(this.C,330);g.S(this,this.TZ);this.x3=g.TR("iv-drawer-header-text",this.Y);this.L=g.TR("iv-drawer-content",this.Y);this.addCueRange(0,
K.videoData.lengthSeconds*1E3,"",function(){x.hR&&eQ(x,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(x.hR=x.X)&&Ke(x)});
this.W2=new g.US(this);g.S(this,this.W2);this.W.addEventListener("videodatachange",this.Rb.bind(this))},anL=function(Y,e){e=e.data;
e.autoOpenMs&&Y.addCueRange(e.autoOpenMs,0x8000000000000,"",function(){eQ(Y,"YOUTUBE_DRAWER_AUTO_OPEN")});
e.autoCloseMs&&Y.addCueRange(e.autoCloseMs,0x8000000000000,"",function(){Ke(Y)});
var K=e.headerText;g.X2(Y.x3,K);Y.B&&(Y.W.Z("player_tooltip_data_title_killswitch")?Y.B.setAttribute("title",K):Y.B.setAttribute("data-tooltip-title",K));e.eventId&&(Y.eventId=e.eventId);Y.X6=g.od(e.trackingParams);Y.S=g.od(e.closeTrackingParams);Y.ud=g.od(e.iconTrackingParams)},UaA=function(Y,e){var K=e.cardId?e.cardId:"cr:"+Y.T,x=Y.W.D().experiments.D4("enable_error_corrections_infocard_web_client");
if(!e.content&&e.teaser.simpleCardTeaserRenderer&&x){var z=e.teaser.simpleCardTeaserRenderer,O=e.icon?e.icon.infoCardIconRenderer:null;if(z.channelAvatar&&z.channelAvatar.thumbnails&&z.channelAvatar.thumbnails.length>0)var T=xJ(z.channelAvatar.thumbnails,22,22).url;e={id:K,timestamp:Y.T,type:"simple",teaserText:g.TC(z.message),teaserDurationMs:Number(e.cueRanges[0].teaserDurationMs),startMs:Number(e.cueRanges[0].startCardActiveMs),autoOpen:!!e.autoOpen,sessionData:{},sponsored:!1,hF:{},YH:null,DD:z.trackingParams?
g.od(z.trackingParams):null,ud:O&&O.trackingParams?g.od(O.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,vE:null,title:"",customMessage:"",url:null,onClickCommand:z.onTapCommand||null,Ru:T};sG(Y,e)}else{var E;if((E=e.content)==null?0:E.simpleCardContentRenderer){if(!e.cueRanges.length)return;T=(z=e.content)==null?void 0:z.simpleCardContentRenderer;z=e.teaser.simpleCardTeaserRenderer;O=e.icon?e.icon.infoCardIconRenderer:null;e={id:K,timestamp:Y.T,type:"simple",teaserText:g.TC(z.message),
teaserDurationMs:Number(e.cueRanges[0].teaserDurationMs),startMs:Number(e.cueRanges[0].startCardActiveMs),autoOpen:!!e.autoOpen,sessionData:zq(Y,K,e,T),sponsored:!1,hF:YJ(T,z,T.command),YH:T.trackingParams?g.od(T.trackingParams):null,DD:z.trackingParams?g.od(z.trackingParams):null,ud:O&&O.trackingParams?g.od(O.trackingParams):null,imageUrl:xJ(T.image.thumbnails,290,290).url,displayDomain:T.displayDomain?g.TC(T.displayDomain):null,showLinkIcon:!!T.showLinkIcon,vE:null,title:T.title?g.TC(T.title):"",
customMessage:T.callToAction?g.TC(T.callToAction):"",url:g.l(T.command,g.p4).url?nU({pause_on_navigation:!Y.context.videoData.isLivePlayback,target:"new",value:g.l(T.command,g.p4).url}):null,onClickCommand:null};sG(Y,e)}else{var u;if((u=e.content)==null?0:u.collaboratorInfoCardContentRenderer){if(!e.cueRanges.length)return;T=(O=e.content)==null?void 0:O.collaboratorInfoCardContentRenderer;z=e.teaser.simpleCardTeaserRenderer;O=e.icon?e.icon.infoCardIconRenderer:null;e={id:K,timestamp:Y.T,type:"collaborator",
teaserText:g.TC(z.message),teaserDurationMs:Number(e.cueRanges[0].teaserDurationMs),startMs:Number(e.cueRanges[0].startCardActiveMs),autoOpen:!!e.autoOpen,sessionData:zq(Y,K,e,T),sponsored:!1,hF:YJ(T,z,T.endpoint),YH:T.trackingParams?g.od(T.trackingParams):null,DD:z.trackingParams?g.od(z.trackingParams):null,ud:O&&O.trackingParams?g.od(O.trackingParams):null,channelId:g.l(T.endpoint,g.IR).browseId,customMessage:T.customText?g.TC(T.customText):null,profileImageUrl:xJ(T.channelAvatar.thumbnails,290,
290).url,title:T.channelName?g.TC(T.channelName):"",metaInfo:[T.subscriberCountText?g.TC(T.subscriberCountText):""],url:nU({pause_on_navigation:!Y.context.videoData.isLivePlayback,target:"new",value:g.l(T.endpoint,g.IR).canonicalBaseUrl?g.l(T.endpoint,g.IR).canonicalBaseUrl:"/channel/"+g.l(T.endpoint,g.IR).browseId}),onClickCommand:null};sG(Y,e)}else{var b;if((b=e.content)==null?0:b.playlistInfoCardContentRenderer){if(!e.cueRanges.length)return;var k;T=(k=e.content)==null?void 0:k.playlistInfoCardContentRenderer;
z=e.teaser.simpleCardTeaserRenderer;O=e.icon?e.icon.infoCardIconRenderer:null;e={id:K,timestamp:Y.T,type:"playlist",teaserText:g.TC(z.message),teaserDurationMs:Number(e.cueRanges[0].teaserDurationMs),startMs:Number(e.cueRanges[0].startCardActiveMs),autoOpen:!!e.autoOpen,sessionData:zq(Y,K,e,T),sponsored:!1,hF:YJ(T,z,T.action),YH:T.trackingParams?g.od(T.trackingParams):null,DD:z.trackingParams?g.od(z.trackingParams):null,ud:O&&O.trackingParams?g.od(O.trackingParams):null,Yx:xJ(T.playlistThumbnail.thumbnails,
258,290).url,customMessage:T.customMessage?g.TC(T.customMessage):null,playlistVideoCount:g.TC(T.playlistVideoCount),title:T.playlistTitle?g.TC(T.playlistTitle):"",metaInfo:[T.channelName?g.TC(T.channelName):"",T.videoCountText?g.TC(T.videoCountText):""],url:nU({pause_on_navigation:!Y.context.videoData.isLivePlayback,target:"new",value:ma6(T.action)}),onClickCommand:null};sG(Y,e)}else{var G;if((G=e.content)==null?0:G.videoInfoCardContentRenderer){if(!e.cueRanges.length)return;var B;T=(B=e.content)==
null?void 0:B.videoInfoCardContentRenderer;z=e.teaser.simpleCardTeaserRenderer;O=e.icon?e.icon.infoCardIconRenderer:null;e={id:K,timestamp:Y.T,type:"video",teaserText:g.TC(z.message),teaserDurationMs:Number(e.cueRanges[0].teaserDurationMs),startMs:Number(e.cueRanges[0].startCardActiveMs),autoOpen:!!e.autoOpen,sessionData:zq(Y,K,e,T),sponsored:!1,hF:YJ(T,z,T.action),YH:T.trackingParams?g.od(T.trackingParams):null,DD:z.trackingParams?g.od(z.trackingParams):null,ud:O&&O.trackingParams?g.od(O.trackingParams):
null,Yx:xJ(T.videoThumbnail.thumbnails,258,290).url,videoDuration:T.lengthString?g.TC(T.lengthString):null,customMessage:T.customMessage?g.TC(T.customMessage):null,title:T.videoTitle?g.TC(T.videoTitle):"",metaInfo:[T.channelName?g.TC(T.channelName):"",T.viewCountText?g.TC(T.viewCountText):""],isLiveNow:!!T.badge,url:nU({pause_on_navigation:!Y.context.videoData.isLivePlayback,target:"new",value:ma6(T.action)}),onClickCommand:null};sG(Y,e)}}}}}Y.T++},xJ=function(Y,e,K){for(var x=-1,z=-1,O=0;O<Y.length;O++){if(Y[O].height===
e||Y[O].width===K)return Y[O];
((Y[O].height||0)<e||(Y[O].width||0)<K)&&(x<0||(Y[x].height||0)<(Y[O].height||0)||(Y[x].width||0)<(Y[O].width||0))?x=O:((Y[O].height||0)>=e||(Y[O].width||0)>=K)&&(z<0||(Y[z].height||0)>(Y[O].height||0)||(Y[z].width||0)>(Y[O].width||0))&&(z=O)}return Y[z>=0?z:x]},zq=function(Y,e,K,x){return{feature:K.feature?K.feature:"cards",
src_vid:Y.context.videoData.videoId,annotation_id:e,ei:Y.context.videoData.eventId||"",itct:x.trackingParams||""}},h9x=function(Y,e){if(e=QJ1(Y,e))e===Y.K&&(Y.K=null),Y.W.removeCueRange(e.Pp.id),g.Rb(e.xt),g.QU(Y.cards,e),Y.uB(),$J(Y)},eQ=function(Y,e,K){if(!Y.X){Y.TZ.show();
Y.g7=new g.S2(function(){g.YI(Y.context.W.getRootNode(),g.aw.IV_DRAWER_OPEN)},0);
Y.g7.start();Y.W2.J(Y.L,"mousewheel",function(T){Y.pF.start();T.preventDefault();T=T||window.event;var E=0;T.type=="MozMousePixelScroll"?E=0==(T.axis==T.HORIZONTAL_AXIS)?T.detail:0:window.opera?E=T.detail:E=T.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?T.wheelDeltaY/-30:T.wheelDeltaY/-1.2:T.wheelDelta/-1.6:T.wheelDeltaY/-3;if(T=E)Y.L.scrollTop+=T});
Y.X=!0;var x=g.Ld();x&&Y.X6&&Y.S&&g.nd(x,[Y.X6,Y.S]);e={TRIGGER_TYPE:e};for(var z=g.a(Y.cards),O=z.next();!O.done;O=z.next())O=O.value,O.Ij||(O.Ij=!0,PX1(Y.context.logger,O.Pp.hF.mJ,e)),x&&g.nd(x,[O.Pp.YH]);pU(Y.W);K&&(Y.U=new g.S2(function(){Y.fF=Y.B;Y.bJ.focus()},330),Y.U.start())}},Ke=function(Y){Y.X&&(Y.TZ.hide(),g.Um(Y.W2),g.Kw(Y.context.W.getRootNode(),g.aw.IV_DRAWER_OPEN),Y.X=!1,pU(Y.W),Y.U&&Y.U.stop(),Y.U=new g.S2(function(){Y.fF&&(Y.fF.focus(),Y.fF=null)},330),Y.U.start())},MTM=function(Y){g.eD(Y.w2(),
[g.aw.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.Yw(Y.W,Y.Y,5);Y.g3();Y.B=g.TR("ytp-cards-button",Y.W.getRootNode());Y.bJ=g.TR("iv-drawer-close-button",Y.Y);Y.isInitialized=!0},NU6=function(Y){Y.nF.push(g.yY("iv-teaser-shown",Y.vB,Y));
Y.nF.push(g.yY("iv-teaser-hidden",Y.I4R,Y));Y.nF.push(g.yY("iv-teaser-clicked",Y.oK,Y));Y.Iq=!0},ZT6=function(Y,e){var K;
return e.onClickCommand&&((K=g.l(e.onClickCommand,g.sbd))==null?void 0:K.targetId)==="engagement-panel-error-corrections"?(Y.xq=e,!0):!1},pGq=function(Y,e){Y.xq=e;
var K=Y.W.getVideoData();if(!K)return!1;K=g.et(K);if(K==null?0:K.markersMap)for(var x,z=0;((x=K)==null?void 0:x.markersMap.length)>z;z++){var O=void 0,T=(O=K)==null?void 0:O.markersMap[z];if(T.key==="ERROR_CORRECTION_MARKERS"&&(O=void 0,(T=(O=T.value)==null?void 0:O.markers)&&T.length>0))return x=void 0,e.startMs=((x=g.l(T[0],g.hGp))==null?void 0:x.timeRangeStartMillis)||0,Y.xq=null,!0}return!1},sG=function(Y,e){if(!ZT6(Y,e)||pGq(Y,e)){var K=cx7(Y,e);
if(K){var x={Pp:e,xt:K.element,Ij:!1};if(e.onClickCommand)Y.W.Z("web_infocards_teaser_show_logging_fix")&&(Y.Iq||NU6(Y),h9x(Y,e.id),K=Y.findLastIndex(x),g.iM(Y.cards,K,0,x));else{Y.isInitialized||MTM(Y);h9x(Y,e.id);var z=Y.findLastIndex(x);g.iM(Y.cards,z,0,x);K.Ri(Y.L,z);Y.uB()}e.autoOpen?Y.addCueRange(e.startMs,0x8000000000000,e.id,function(){Y.X||(Y.K=x,$J(Y),VTn(Y,x),eQ(Y,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(K=Y.context.W.getCurrentTime()*1E3,K<5E3&&K>e.startMs&&CXA(Y,x),Y.addCueRange(e.startMs,
e.startMs+1,e.id,function(){CXA(Y,x)}),$J(Y))}}},cx7=function(Y,e){switch(e.type){case "simple":Y=Y.LF;
var K=e.displayDomain?{N:"div",j:"iv-card-image-text",Qq:e.displayDomain}:void 0;var x=BUd(e);K={N:"div",v2:["iv-card"],G:[{N:"a",j:"iv-click-target",V:{href:e.url?qR(e.url)||"":""},G:[yV(e.imageUrl,K),{N:"div",j:"iv-card-content",G:[wH("h2",void 0,e.title),x]}]}]};K=new g.d(K);I2(Y,g.$C("iv-click-target",K.element),e,e.url);e=K;break;case "collaborator":Y=Y.LF;K={N:"div",v2:["iv-card","iv-card-channel"],G:[{N:"a",v2:["iv-click-target"],V:{href:qR(e.url)||"","data-ytid":e.channelId},G:[yV(e.profileImageUrl),
{N:"div",j:"iv-card-content",G:[oTU(e),{N:"h2",j:"iv-card-primary-link",Qq:e.title},Ga6(e)]}]}]};K=new g.d(K);I2(Y,g.$C("iv-click-target",K.element),e,e.url);e=K;break;case "playlist":Y=Y.LF;K={N:"div",v2:["iv-card","iv-card-playlist"],G:[{N:"a",j:"iv-click-target",V:{href:qR(e.url)||""},G:[yV(e.Yx,{N:"div",j:"iv-card-image-overlay",G:[{N:"span",j:"iv-card-playlist-video-count",Qq:e.playlistVideoCount}]}),{N:"div",j:"iv-card-content",G:[oTU(e),wH("h2","iv-card-primary-link",e.title),Ga6(e)]}]}]};
K=new g.d(K);I2(Y,g.$C("iv-click-target",K.element),e,e.url);e=K;break;case "productListing":Y=Y.LF;var z=e.offers.length!=0;K=["iv-card"];x="";var O=BUd(e);z&&(K.push("iv-card-product-listing"),x="iv-card-primary-link",O=e.offers[0],z=[],O.price&&z.push({N:"div",j:"iv-card-offer-price",Qq:O.price}),O.merchant&&z.push({N:"div",j:"iv-card-offer-merchant",Qq:O.merchant}),O={N:"div",G:z});z=e.url?qR(e.url)||"":"";K={N:"div",v2:K,V:{tabindex:"0"},G:[{N:"a",v2:["iv-card-image","iv-click-target"],V:{style:"background-image: url("+
e.imageUrl+");",href:z,"aria-hidden":"true",tabindex:"-1"}},{N:"div",j:"iv-card-content",G:[e.sponsored?{N:"div",j:"iv-card-sponsored",G:["\uc2a4\ud3f0\uc11c",{N:"div",j:"iv-ad-info-container",G:[{N:"div",j:"iv-ad-info",Qq:"{{adInfo}}"},{N:"div",j:"iv-ad-info-icon-container",G:[{N:"div",j:"iv-ad-info-icon"},{N:"div",j:"iv-ad-info-callout"}]}]}]}:"",{N:"a",j:"iv-click-target",V:{href:z},G:[wH("h2",x,e.title),O]}]}]};K=new g.d(K);x=g.ob("span");g.X2(x,"\ub3d9\uc601\uc0c1\uacfc \uad00\ub828\uc774 \uc788\ub294 \uac83\uc73c\ub85c \ubcf4\uc5ec \uc81c\ud488\uc774 \ud45c\uc2dc\ub418\uc5c8\uc2b5\ub2c8\ub2e4. Google\uc5d0\uc11c \ud310\ub9e4\uc790\ub85c\ubd80\ud130 \ubcf4\uc0c1\uc744 \ubc1b\uc744 \uc218\ub3c4 \uc788\uc2b5\ub2c8\ub2e4.");
K.DO(x,"adInfo");I2(Y,g.$C("iv-click-target",K.element),e,e.url);e=K;break;case "video":Y=Y.LF;x=e.videoDuration?{N:"span",j:"iv-card-video-duration",Qq:e.videoDuration}:void 0;O=e.isLiveNow?{N:"span",v2:["yt-badge","yt-badge-live"],Qq:"\uc2e4\uc2dc\uac04"}:null;z={N:"div",v2:["iv-card","iv-card-video"],G:[{N:"a",j:"iv-click-target",V:{href:((K=e.url)==null?void 0:qR(K))||""},G:[yV(e.Yx,x),{N:"div",j:"iv-card-content",G:[oTU(e),wH("h2","iv-card-primary-link",e.title),Ga6(e),O]}]}]};K=new g.d(z);I2(Y,
g.$C("iv-click-target",K.element),e,e.url);e=K;break;default:return null}return e},gTn=function(Y){if(Y.K)return Y.K.Pp.type==="productListing";
if(Y.W.Z("enable_wn_infocards")){var e;return!((e=Y.cards)==null||!e.length)&&g.R0(Y.cards,function(K){return K.Pp.type==="productListing"})}return g.R0(Y.cards,function(K){return K.Pp.type==="productListing"})},$J=function(Y){g.s$(Y.W.getRootNode(),"ytp-cards-shopping-active",gTn(Y))},CXA=function(Y,e){if(!g.tA(Y.W.getRootNode(),"ytp-cards-teaser-shown")){if(Y.K!==e){var K=g.Ld(),x=Y.K?Y.K.Pp.ud:Y.ud;
K&&x&&g.w1(K,[x]);Y.K=e;$J(Y)}(K=Y.isInitialized&&Y.w2().style.display=="none")||(K=Y.context.W.getPlayerState(),x=K===0&&Y.context.W.getCurrentTime()===0,K=!(K===1||K===3||x));if(!K&&e.Pp.teaserDurationMs){var z;K={teaserText:e.Pp.teaserText,durationMs:e.Pp.teaserDurationMs,onClickCommand:e.Pp.onClickCommand,Ru:(z=e.Pp.Ru)!=null?z:null};Y.W.mp(!0,K)}Y.uJ.isActive()||((!Y.X||!Y.pF.isActive()&&Y.Yq)&&VTn(Y,e),Y.uJ.start(910+e.Pp.teaserDurationMs))}},VTn=function(Y,e){Y.C.aq?(e=new AO([0,
Y.L.scrollTop],[0,e.xt.offsetTop],600,JBa),Y.context.X.listen(e,"animate",function(K){Y.L.scrollTop=K.y}),Y.context.X.listen(e,"finish",function(K){Y.L.scrollTop=K.y}),e.play()):(Y.C.iP(!0),Y.L.scrollTop=e.xt.offsetTop,Y.C.iP(!1))},OG=function(Y){return Y.K&&Y.K.Pp?Y.K.Pp:Y.cards[0]&&Y.cards[0].Pp?Y.cards[0].Pp:null},QJ1=function(Y,e){return g.mZ(Y.cards,function(K){return K.Pp.id===e})},Tq=function(Y,e,K){Db.call(this,Y,e);
this.annotation=K;this.isActive=!1},Ax6=function(Y){var e=Y.annotation.data;
"start_ms"in e&&"end_ms"in e&&Y.addCueRange(Number(e.start_ms),Number(e.end_ms),Y.annotation.id,function(){Y.show()},function(){Y.hide()})},Fu=function(Y,e,K){Tq.call(this,Y,e,K);
this.L=null;this.T=!1;this.X=null;this.Y=!1;this.K=this.U=this.B=null},vTz=function(Y,e){var K=K===void 0?0:K;
var x=cBL(e).width;g.Ib(e,x);K=new jp0(e,[x,e.offsetTop],[x-x-K,e.offsetTop],200,i9M);g.S(Y,K);Y.context.X.listen(K,"begin",function(){g.x1(e,!0)});
K.play()},iTM=function(Y,e){if(e.channel_name){var K=Y.createElement({N:"div",
v2:["iv-branding-context-name"],Qq:e.channel_name}),x=Y.createElement({N:"div",v2:["iv-branding-context-subscribe"]}),z=e.standalone_subscribe_button_data;z&&(Y.K=new g.$4(z.subscribeText,z.subscribeCount,z.unsubscribeText,z.unsubscribeCount,!!z.enabled,!!z.classic,e.channel_id,!!z.subscribed,z.feature,e.session_data.itct,Y.context.W,!1),Y.K.Ri(x));var O=Y.createElement({N:"div",v2:["iv-branding-context-subscribe-caret"]}),T=Y.createElement({N:"div",v2:["branding-context-container-inner"]});T.appendChild(O);
T.appendChild(K);T.appendChild(x);g.x1(T,!1);var E=Y.createElement({N:"div",v2:["branding-context-container-outer"]});E.appendChild(T);g.ln(E,"right",e.image_width+"px");g.Bl(Y.w2(),E);Y.X=new g.S2(function(){rxx(Y,T,E)},500);
g.S(Y,Y.X);Y.context.K.listen(Y.w2(),"mouseover",function(){jJz(Y,T,E,O,e.image_height)});
Y.context.K.listen(Y.w2(),"mouseout",function(){Y.X.start()})}},jJz=function(Y,e,K,x,z){Y.X.stop();
if(!Y.Y){var O=g.Kh(e);Y.K||(e.style.width=g.yo(O.width,!0),K.style.width=g.yo(O.width,!0));g.ln(x,"top",O.height-Math.max(Math.min(O.height,z)/2+10,20)+"px");g.ln(x,"right","1px");Y.Y=!0;g.x1(e,!0);Y.B=new g.S2(function(){g.YI(this.w2(),"iv-branding-active")},0,Y);
Y.B.start()}},rxx=function(Y,e,K){g.Kw(Y.w2(),"iv-branding-active");
Y.U=new g.S2(function(){g.x1(e,!1);Y.K||(K.style.width=g.yo(0,!0))},250);
Y.U.start();Y.Y=!1},JxP=function(Y,e,K,x,z,O,T){this.K=Y;
this.X=e;this.ai=K;this.videoData=x;this.logger=z;this.W=O;this.L=T},SOx=function(Y,e,K){Tq.call(this,Y,e,K);
var x=this;this.S=this.isCollapsed=this.C=!1;this.U=5E3;this.L=this.X=this.K=this.Y=null;this.T=this.createElement({N:"div",v2:["iv-promo-contents"]});this.B=new g.S2(function(){x.K.setAttribute("aria-hidden","true");g.x1(x.X,!1);g.x1(x.L,!0)},700,this);
g.S(this,this.B)},HTz=function(Y){var e=Y.annotation.data;
if(Y.annotation.style==="cta")var K=6;else if(Y.annotation.style==="video"||Y.annotation.style==="playlist")K=7;Y.U=e.collapsedelay_ms||Y.U;var x=["iv-promo","iv-promo-inactive"];Y.w2().setAttribute("aria-hidden","true");Y.w2().setAttribute("aria-label","\ud504\ub85c\ubaa8\uc158");Y.w2().tabIndex=0;var z=Y.annotation.Ne(),O=e.image_url;if(O){var T=Y.createElement({N:"div",v2:["iv-promo-img","iv-click-target"]});O=Y.createElement({N:"img",V:{src:O,"aria-hidden":"true"}});T.appendChild(O);e.video_duration&&
!e.is_live?(O=Y.createElement({N:"span",j:"iv-promo-video-duration",Qq:e.video_duration}),T.appendChild(O)):e.playlist_length&&(O=Y.createElement({N:"span",j:"iv-promo-playlist-length",Qq:e.playlist_length.toString()}),T.appendChild(O));z&&tO(Y,T,z,Y.annotation.id,e.session_data,void 0,K)}z?(O=Y.createElement({N:"a",j:"iv-promo-txt"}),g.En(O,qR(z)),Y.K=O):Y.K=Y.createElement({N:"div",j:"iv-promo-txt"});switch(Y.annotation.style){case "cta":case "website":var E=Y.createElement({N:"p",G:[{N:"strong",
Qq:e.text_line_1}]});var u=Y.createElement({N:"p",G:[{N:"span",j:"iv-promo-link",Qq:e.text_line_2}]});if(O=e.text_line_3){x.push("iv-promo-website-card-cta-redesign");var b=Y.createElement({N:"button",v2:["iv-promo-round-expand-icon","ytp-button"]});O=Y.createElement({N:"button",v2:["iv-button","iv-promo-button"],G:[{N:"span",j:"iv-button-content",Qq:O}]});var k=Y.createElement({N:"div",j:"iv-promo-button-container"});k.appendChild(O);z&&tO(Y,Y.w2(),z,Y.annotation.id,e.session_data,void 0,K)}g.YI(Y.K,
"iv-click-target");z&&tO(Y,Y.K,z,Y.annotation.id,e.session_data,void 0,K);break;case "playlist":case "video":E=Y.createElement({N:"p",G:[{N:"span",Qq:e.text_line_1}]}),u=Y.createElement({N:"p",G:[{N:"strong",Qq:e.text_line_2}]}),e.is_live&&(E=u,u=Y.createElement({N:"span",v2:["yt-badge","iv-promo-badge-live"],Qq:"\uc2e4\uc2dc\uac04"})),g.YI(Y.K,"iv-click-target"),z&&tO(Y,Y.K,z,Y.annotation.id,e.session_data,void 0,K),x.push("iv-promo-video")}E&&Y.K.appendChild(E);u&&Y.K.appendChild(u);Y.T.appendChild(Y.K);
k&&Y.T.appendChild(k);K=Y.createElement({N:"div",j:"iv-promo-actions"});Y.L=Y.createElement({N:"button",v2:["iv-promo-expand","ytp-button"]});Y.L.title="\ud655\uc7a5";Y.context.K.listen(Y.L,"click",function(G){Wwq(Y,5E3,G)});
K.appendChild(Y.L);g.x1(Y.L,!1);Y.context.K.listen(Y.w2(),"mouseover",Y.TF,Y);Y.context.K.listen(Y.w2(),"mouseout",Y.ZS,Y);Y.context.K.listen(Y.w2(),"touchend",function(G){Wwq(Y,5E3,G)});
Y.X=Y.createElement({N:"button",v2:["iv-promo-close","ytp-button"]});Y.X.title="\ub2eb\uae30";Y.context.K.listen(Y.X,"click",Y.annotation.style==="cta"&&e.text_line_3?Y.s1:Y.gk,Y);K.appendChild(Y.X);g.eD(Y.w2(),x);T&&(g.Bl(Y.w2(),T),b&&T.appendChild(b));g.Bl(Y.w2(),Y.T);g.Bl(Y.w2(),K)},Wwq=function(Y,e,K){K.stopPropagation();
lna(Y);daa(Y,e);Y.K.focus()},qOL=function(Y){Y.isCollapsed||Y.S||Y.Y||(g.YI(Y.w2(),"iv-promo-collapsed"),Y.isCollapsed=!0,Y.B.start())},lna=function(Y){Y.B.stop();
Y.isCollapsed&&(g.xI(Y.w2(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),Y.isCollapsed=!1,Y.K&&Y.K.removeAttribute("aria-hidden"),g.x1(Y.L,!1),g.x1(Y.X,!0))},daa=function(Y,e){Y.Y||(Y.Y=g.Al(function(){nT1(this);
qOL(this)},e,Y))},nT1=function(Y){Y.Y&&(g.t8.clearTimeout(Y.Y),Y.Y=null)},wGq=function(Y){this.W=Y},PX1=function(Y,e,K){e&&(K?EG(Y,e.map(function(x){return g.hA(x,K)})):EG(Y,e))},EG=function(Y,e,K,x){var z=1,O=void 0,T=-1;
if(K){var E=!1;O=function(){z--;z||E||(clearTimeout(T),E=!0,K())};
T=setTimeout(function(){E=!0;K()},1E3)}e=g.a(e||[]);
for(var u=e.next();!u.done;u=e.next())u=u.value,z++,g.pG(u,O);x&&(z++,x!==0&&Y.W.sendVideoStatsEngageEvent(x,O))},yxA=function(Y){g.Ms.call(this,Y);
var e=this;this.nF=this.S=!1;this.loadNumber=0;this.U={};this.logger=new wGq(this.player);this.Y=new g.US(this);this.B=this.T=null;this.events=new g.US(this);this.VX=this.C=this.K=null;this.xq=[];g.S(this,this.Y);this.Y.J(this.player,"onVideoAreaChange",function(){e.publish("onVideoAreaChange")});
this.Y.J(this.player,"onHideControls",function(){e.publish("onHideControls")});
this.Y.J(this.player,"onShowControls",function(){e.publish("onShowControls")});
this.Y.J(this.player,"resize",function(x){e.publish("resize",x)});
this.Y.J(this.player,"presentingplayerstatechange",function(x){e.publish("presentingplayerstatechange",x)});
this.subscribe("presentingplayerstatechange",this.YK,this);this.subscribe("resize",this.jw,this);this.player.D().Yq.subscribe("vast_info_card_add",this.l8,this);g.S(this,this.events);this.LF=this.createElement({N:"div",j:"video-custom-annotations"});this.L=new g.d({N:"div",v2:["ytp-player-content","ytp-iv-player-content"]});g.S(this,this.L);g.Yw(this.player,this.L.element,4);this.L.hide();this.X=new g.d({N:"div",v2:["ytp-iv-video-content"]});g.S(this,this.X);Y=this.createElement({N:"div",j:"video-annotations"});
Y.appendChild(this.LF);this.X.element.appendChild(Y);this.JT()&&this.load();var K=this.createElement({N:"style"});(g.zR("HEAD")[0]||document.body).appendChild(K);this.addOnDisposeCallback(function(){g.Rb(K)});
if(Y=K.sheet)Y.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),Y.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),Y.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),Y.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),Y.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),Y.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),Y.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),Y.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),Y.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),Y.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},Inn=function(Y){Y=Y.createElement({N:"div",
v2:["annotation","annotation-type-custom"]});g.x1(Y,!1);return Y},Dad=function(Y,e){e=!e.isCued()&&!g.n(e,1024);
Y.L.iP(e);Y.X.iP(e)},tT1=function(Y,e,K){Y.S=!0;
Y.B=g.RE(e,K)},YWn=function(Y,e){for(var K={},x=g.a(e.attributes),z=x.next();!z.done;z=x.next())z=z.value,K[z.name]=z.nodeValue;
for(x=0;x<e.childNodes.length;x++)if(z=e.childNodes[x],g.$x(z)&&z.nodeType==1){if(K[z.tagName])var O=K[z.tagName];else if(z.tagName==="data"){z.childNodes.length>0&&(O=z.childNodes[0].nodeValue,K[z.tagName]=typeof O==="string"?O.trim():O);continue}else O=[],K[z.tagName]=O;z&&z.tagName==="TEXT"?z.childNodes.length===1&&z.childNodes[0].nodeType===3?O.push(z.childNodes[0].nodeValue):O.push(""):z&&O.push(YWn(Y,z))}return K},sHA=function(Y){var e=Y.player.getVideoData();
if(e.W2){var K=Y.player.D().Yq.get(e.videoId);if(K){var x={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(z,O,T){z=Y.loadNumber;O=e.videoId;Y.loaded&&Y.loadNumber===z&&Y.player.getVideoData().videoId===O&&(T=g.TN(T)&&T.responseXML?T.responseXML:null)&&eV6(Y,T)}};
g.n7()&&(x.onFinish=KYM(Y,x.onFinish));x.postParams={ic_only:"1"};xE1(x,K);Y.S=!0;g.RE(e.W2,x)}}},xE1=function(Y,e){Y.method="POST";
Y.postParams=Y.postParams||{};e.C1&&(Y.postParams.ic_coll=e.C1);e.Id&&(Y.postParams.ic_xml=e.Id);e.ri&&(Y.postParams.ic_track=e.ri)},zVL=function(Y){var e=new g.d({N:"div"});
g.x1(e.element,!1);var K=new XG6(Y.player,e.element,uP(Y));g.S(K,e);e.Ri(Y.L.element);K.au();return K},OJx=function(Y,e){var K,x;
if(e=(K=e.getWatchNextResponse())==null?void 0:(x=K.cards)==null?void 0:x.cardCollectionRenderer)Y.nF=!0,$Ea(Y,e),e.headerText&&Y.VX&&(K=g.TC(e.headerText),Y.player.Z("player_tooltip_data_title_killswitch")?Y.VX.setAttribute("title",K):Y.VX.setAttribute("data-tooltip-title",K))},uP=function(Y){if(!Y.C){var e=new SHL(Y);
g.S(Y,e);var K=new g.kZ(Y);g.S(Y,K);Y.C=new JxP(e,K,Y.player.D(),Y.player.getVideoData(),Y.logger,Y.player,Y.X9)}return Y.C},eV6=function(Y,e){var K=!1,x=e.getElementsByTagName("annotations");
if(x&&!(x.length<1)&&(x=x[0].getAttribute("itct"))){var z=g.Ld();if(z){var O=g.B1();O&&g.lN(g.r1)(void 0,z,O,[g.od(x)])}}e=e.getElementsByTagName("annotation");for(x=0;x<e.length;x++){O=YWn(Y,e[x]);z=null;try{if(O){var T=O.id,E=/.+/;var u=typeof T==="string"&&E!=null&&T!=null&&T.match(E)?T:"";var b=dH(O.type,TK1),k=dH(O.style,FYn),G=sJA(O.data),B=G.length!==0?JSON.parse(G):{};var L=O.action;O=ETU;if(L==null)var f=null;else if(g.zP(L)){E=[];for(var U=g.a(L),h=U.next();!h.done;h=U.next()){var Z=O(h.value);
Z&&E.push(Z)}f=E}else{var N=O(L);f=N?[N]:[]}z=u&&b?new uiU(u,b,k,f,B):null}else z=null}catch($O){}if(z)if(z.type==="branding"||z.type==="promotion"){O=Y;E=z;var V=Inn(O),r=null;switch(E.type){case "branding":if(O.player.D().Sx)break;O.player.Z("web_player_overlay_positioned_layout")?(V.setAttribute("data-overlay-order","11"),O.player.VC(V,4,!0)):O.L.element.appendChild(V);r=new Fu(V,uP(O),E);break;case "promotion":g.Yw(O.player,V,4),r=new SOx(V,uP(O),E)}r&&r.au();if(O=r)g.S(Y,O),Y.U[z.id]=O}else if(z.type===
"card"||z.type==="drawer"){Y.K||(Y.K=zVL(Y),g.S(Y,Y.K));if(z.type==="card"){V=Y.K;var H=(K=z)&&K.data&&K.data.card_type;z=K.data;if(H)switch(O=z.tracking||{},O={mJ:O.impression,click:O.click,close:O.close,qq:O.teaser_impression,LH:O.teaser_click},E=z.tracking_params||{},r=null,H){case "collaborator":K={id:K.id,timestamp:z.timestamp||0,type:z.card_type,teaserText:z.teaser_text,teaserDurationMs:z.teaser_duration_ms,startMs:z.start_ms,autoOpen:z.auto_open||!1,sessionData:z.session_data||{},sponsored:z.sponsored||
!1,hF:O,YH:E.card?g.od(E.card):null,DD:E.teaser?g.od(E.teaser):null,ud:E.icon?g.od(E.icon):null,channelId:z.channel_id,customMessage:z.custom_message?z.custom_message:null,profileImageUrl:z.image_url,title:z.title,metaInfo:z.meta_info,url:nU({pause_on_navigation:z.pause_on_navigation,target:z.target||"new",value:z.url}),onClickCommand:null};sG(V,K);break;case "playlist":K={id:K.id,timestamp:z.timestamp||0,type:z.card_type,teaserText:z.teaser_text,teaserDurationMs:z.teaser_duration_ms,startMs:z.start_ms,
autoOpen:z.auto_open||!1,sessionData:z.session_data||{},sponsored:z.sponsored||!1,hF:O,YH:E.card?g.od(E.card):null,DD:E.teaser?g.od(E.teaser):null,ud:E.icon?g.od(E.icon):null,Yx:z.image_url,playlistVideoCount:z.playlist_video_count,customMessage:z.custom_message?z.custom_message:null,title:z.title,metaInfo:z.meta_info,url:nU({pause_on_navigation:z.pause_on_navigation,target:z.target||"new",value:z.url}),onClickCommand:null};sG(V,K);break;case "productListing":z.signin_url&&(r=nU({target:"current",
value:z.signin_url}));H=[];for(var I=z.offers||[],w=0;w<I.length;w++)H.push(new Lwz(g.cK(I[w].merchant),g.cK(I[w].price)));K={id:K.id,timestamp:z.timestamp||0,type:z.card_type,teaserText:z.teaser_text,teaserDurationMs:z.teaser_duration_ms,startMs:z.start_ms,autoOpen:z.auto_open||!1,sessionData:z.session_data||{},sponsored:z.sponsored||!1,hF:O,YH:E.card?g.od(E.card):null,DD:E.teaser?g.od(E.teaser):null,ud:E.icon?g.od(E.icon):null,imageUrl:z.image_url,displayDomain:z.display_domain?z.display_domain:
null,showLinkIcon:!!z.show_link_icon,vE:z.button_icon_url?z.button_icon_url:null,title:z.title,customMessage:z.custom_message?z.custom_message:null,url:nU({pause_on_navigation:z.pause_on_navigation,target:z.target||"new",value:z.url}),tQo:r,fJd:z.signin_title?z.signin_title:void 0,qOT:z.signin_message?z.signin_message:void 0,offers:H,onClickCommand:null};sG(V,K);break;case "simple":K={id:K.id,timestamp:z.timestamp||0,type:z.card_type,teaserText:z.teaser_text,teaserDurationMs:z.teaser_duration_ms,
startMs:z.start_ms,autoOpen:z.auto_open||!1,sessionData:z.session_data||{},sponsored:z.sponsored||!1,hF:O,YH:E.card?g.od(E.card):null,DD:E.teaser?g.od(E.teaser):null,ud:E.icon?g.od(E.icon):null,imageUrl:z.image_url,displayDomain:z.display_domain?z.display_domain:null,showLinkIcon:!!z.show_link_icon,vE:z.button_icon_url?z.button_icon_url:null,title:z.title,customMessage:z.custom_message?z.custom_message:null,url:nU({pause_on_navigation:z.pause_on_navigation,target:z.target||"new",value:z.url}),onClickCommand:null};
sG(V,K);break;case "video":K={id:K.id,timestamp:z.timestamp||0,type:z.card_type,teaserText:z.teaser_text,teaserDurationMs:z.teaser_duration_ms,startMs:z.start_ms,autoOpen:z.auto_open||!1,sessionData:z.session_data||{},sponsored:z.sponsored||!1,hF:O,YH:E.card?g.od(E.card):null,DD:E.teaser?g.od(E.teaser):null,ud:E.icon?g.od(E.icon):null,Yx:z.image_url,videoDuration:z.video_duration||null,customMessage:z.custom_message?z.custom_message:null,title:z.title,metaInfo:z.meta_info,isLiveNow:!!z.is_live_now,
url:nU({pause_on_navigation:z.pause_on_navigation,target:z.target||"new",value:z.url}),onClickCommand:null},sG(V,K)}}else anL(Y.K,z);K=!0}}K&&(pU(Y.player),Y.jw())},$Ea=function(Y,e){var K=!1;
Y.K||(Y.K=zVL(Y),g.S(Y,Y.K));for(var x=g.a(e.cards||[]),z=x.next();!z.done;z=x.next())z=z.value,z.cardRenderer&&(UaA(Y.K,z.cardRenderer),K=!0);if(K){var O;(O=Y.player.getVideoData())!=null&&g.sN(O)||(K=Y.K,x=e.headerText?g.TC(e.headerText):"",g.X2(K.x3,x),K.B&&(K.W.Z("player_tooltip_data_title_killswitch")?K.B.setAttribute("title",x):K.B.setAttribute("data-tooltip-title",x)),K.context.videoData.eventId&&(K.eventId=K.context.videoData.eventId),K.X6=e.trackingParams?g.od(e.trackingParams):null,K.S=
e.closeButton.infoCardIconRenderer.trackingParams?g.od(e.closeButton.infoCardIconRenderer.trackingParams):null,K.ud=e.icon.infoCardIconRenderer.trackingParams?g.od(e.icon.infoCardIconRenderer.trackingParams):null,Y.jw());pU(Y.player)}},Esz=function(Y,e,K,x,z){if(!Y.player.D().Sx){var O=[];
e.navigationEndpoint&&g.l(e.navigationEndpoint,g.IR)&&g.l(e.navigationEndpoint,g.IR).browseId&&O.push(new OTP("openUrl","click",new z9A("/channel/"+g.l(e.navigationEndpoint,g.IR).browseId,"new",!0,!0)));var T=e.watermark.thumbnails[0];x={channel_name:e.channelName,end_ms:e.endTimeMs,image_height:T.height,image_type:1,image_url:T.url,image_width:T.width,is_mobile:!1,session_data:{annotation_id:K,ei:z,feature:"iv",itct:e.trackingParams,src_vid:x},start_ms:e.startTimeMs};if(e.subscribeButton&&g.l(e.subscribeButton,
g.Dt)){x.channel_id=g.l(e.subscribeButton,g.Dt).channelId;var E;e=g.l(e.subscribeButton,g.Dt);T=z=null;e.subscribed?(e.subscriberCountWithUnsubscribeText&&(z=g.TC(e.subscriberCountWithUnsubscribeText)),e.subscriberCountText&&(T=g.TC(e.subscriberCountText))):(e.subscriberCountText&&(z=g.TC(e.subscriberCountText)),e.subscriberCountWithSubscribeText&&(T=g.TC(e.subscriberCountWithSubscribeText)));var u,b=((u=g.l((E=e.signInEndpoint)==null?void 0:E.commandMetadata,g.a_))==null?void 0:u.url)||"";E={subscribeText:g.TC(e.unsubscribedButtonText),
subscribeCount:z||"",unsubscribeText:g.TC(e.subscribedButtonText),unsubscribeCount:T||"",enabled:e.enabled||!1,classic:!1,subscribed:e.subscribed||!1,feature:"iv",signInUrl:b};x.standalone_subscribe_button_data=E}O=new uiU(K,"branding","branding",O,x);E=Inn(Y);Y.player.Z("web_player_overlay_positioned_layout")?(E.setAttribute("data-overlay-order","11"),Y.player.VC(E,4,!0)):Y.L.element.appendChild(E);O=new Fu(E,uP(Y),O);O.au();g.S(O,O);Y.U[K]=O}},KYM=function(Y,e){return function(){var K=g.im.apply(0,
arguments);
Y.qT()||Y.xq.push(g.g6.S1(function(){e.apply(null,g.oS(K))}))}},uB0=function(Y){return Y==="annotation-editor"||Y==="live-dashboard"};
g.d0.prototype.mp=g.sp(39,function(Y,e){var K=g.ii(this.Rq());K&&K.mp(Y,e)});
var VV={},CU=null;g.GP(AO,g.zX);g.R=AO.prototype;g.R.getDuration=function(){return this.duration};
g.R.play=function(Y){if(Y||this.K==0)this.progress=0,this.coords=this.L;else if(this.isPlaying())return!1;gH(this);this.startTime=Y=g.kx();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.Y=this.startTime;this.progress||this.Nr();this.Rm("play");this.isPaused()&&this.Rm("resume");this.K=1;var e=g.TP(this);e in VV||(VV[e]=this);gLz();ABP(this,Y);return!0};
g.R.stop=function(Y){gH(this);this.K=0;Y&&(this.progress=1);vLZ(this,this.progress);this.onStop();this.zk()};
g.R.pause=function(){this.isPlaying()&&(gH(this),this.K=-1,this.Rm("pause"))};
g.R.KF=function(){this.K==0||this.stop(!1);this.Rm("destroy");AO.FH.KF.call(this)};
g.R.destroy=function(){this.dispose()};
g.R.JA=function(){this.Rm("animate")};
g.R.Rm=function(Y){this.dispatchEvent(new rBd(Y,this))};
g.GP(rBd,g.lz);g.GP(vh,AO);vh.prototype.X=function(){};
vh.prototype.JA=function(){this.X();vh.FH.JA.call(this)};
vh.prototype.zk=function(){this.X();vh.FH.zk.call(this)};
vh.prototype.Nr=function(){this.X();vh.FH.Nr.call(this)};
g.GP(jp0,vh);jp0.prototype.X=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.m(SHL,g.J);g.R=SHL.prototype;g.R.listen=function(Y,e,K,x){K=(0,g.E1)(K,x||this.L);Y=g.Bp(Y,e,K);this.K.push(Y);return Y};
g.R.Az=function(Y,e,K,x){K=(0,g.E1)(K,x||this.L);Y=V4L(Y,e,K);this.K.push(Y);return Y};
g.R.oo=function(Y){g.L7(Y);g.QU(this.K,Y)};
g.R.removeAll=function(){g.L7(this.K);this.K.length=0};
g.R.KF=function(){this.removeAll();g.J.prototype.KF.call(this)};g.m(lpx,g.Ms);g.R=lpx.prototype;g.R.load=function(){g.Ms.prototype.load.call(this);if(!iw(this)){var Y=g.qac(this.player.getVideoData());Y?(Y=H9n(Y,dlz(this)),JO(this,Y,!1)):qHq(this)}};
g.R.unload=function(){JO(this,null);this.Y&&(this.Y.abort(),this.Y=null);g.Ms.prototype.unload.call(this)};
g.R.kC=function(Y,e){return iw(this)?Y==="loadCustomEndscreenRenderer"?(Y=H9n(e,"new"),JO(this,Y),!0):null:null};
g.R.getOptions=function(){return iw(this)?["loadCustomEndscreenRenderer"]:[]};
g.R.DK=function(){if(this.endscreen&&this.endscreen.elements){var Y=this.player.getVideoContentRect();if(Y&&Y.width!==0&&Y.height!==0){var e=this.player.getPlayerSize();if(e&&e.width!==0&&e.height!==0){var K=Y.width/Y.height;var x=0;for(var z=-1,O=0;O<bJU.length;O++){var T=Math.abs(e.width-bJU[O]);if(z===-1||x>=T)z=O,x=T}x=kod[z];this.X&&g.ln(this.X.element,"outline-width",Math.max(e.width,e.height)+"px");for(e=0;e<this.endscreen.elements.length;++e)if(O=this.endscreen.elements[e].id,z=this.L[O],
T=this.U[O],z&&T){var E=T.width*K/T.aspectRatio,u=Math.round(T.width*Y.width);O=Math.round(E*Y.height);var b=Y.left+Math.round(T.left*Y.width),k=Y.top+Math.round(T.top*Y.height);g.en(z.element,u,O);g.Ib(z.element,b,k);g.xI(z.element,os0);u>256||O>256?g.YI(z.element,"ytp-ce-large-round"):u>96||O>96?g.YI(z.element,"ytp-ce-medium-round"):g.YI(z.element,"ytp-ce-small-round");g.xI(z.element,Go7);u=T.left+T.width/2;T=T.top+E/2;g.YI(z.element,u<=.5&&T<=.5?"ytp-ce-top-left-quad":u>.5&&T<=.5?"ytp-ce-top-right-quad":
u<=.5&&T>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.xI(z.element,kod);g.YI(z.element,x);(z=g.Oj(document,"div","ytp-ce-expanding-overlay-body",z.element)[0])&&g.ln(z,"height",O+"px")}}}}};
g.R.onCueRangeEnter=function(Y){if(this.endscreen)if(Y.getId()==="ytp-ce-in-endscreen")lw(this,this.endscreen.impressionUrls),(Y=g.Ld())&&this.endscreen.visualElement&&g.qI(Y,this.endscreen.visualElement),this.K&&(g.YI(this.K,"ytp-ce-element-show"),this.K.removeAttribute("aria-hidden"),this.player.xo()?g.YI(this.K,"ytp-ce-hide-button-lower"):g.Kw(this.K,"ytp-ce-hide-button-lower"));else{Y=Y.getId().substring(15);var e=this.L[Y],K=this.U[Y];g.YI(e.element,"ytp-ce-element-show");e.element.removeAttribute("aria-hidden");
e=this.player.getRootNode();g.YI(e,"ytp-ce-shown");lw(this,K.impressionUrls);(e=g.Ld())&&g.qI(e,K.visualElement);this.player.D().S&&this.player.O4("endscreenelementshown",Y)}};
g.R.onCueRangeExit=function(Y){if(Y.getId()==="ytp-ce-in-endscreen")this.K&&(g.Kw(this.K,"ytp-ce-element-show"),this.K.setAttribute("aria-hidden","true"));else{Y=Y.getId().substring(15);var e=this.L[Y];g.Kw(e.element,"ytp-ce-element-show");e.element.setAttribute("aria-hidden","true");e=this.player.getRootNode();g.Kw(e,"ytp-ce-shown");this.player.D().S&&this.player.O4("endscreenelementhidden",Y)}};
g.R.ETq=function(Y){var e=this;Y.target===window&&(new g.S2(function(){for(var K=g.a(Object.values(e.L)),x=K.next();!x.done;x=K.next())g.xI(x.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.R.iP=function(Y){for(var e=g.a(Object.values(this.L)),K=e.next();!K.done;K=e.next())K=K.value,Y?K.element.setAttribute("hidden",""):K.element.removeAttribute("hidden")};
g.R.a57=function(Y){this.K&&this.player.getRootNode().removeChild(this.K);Y&&(g.YI(Y,"ytp-ce-hide-button-container"),this.K=Y,g.Yw(this.player,this.K,4))};
var bJU=[346,426,470,506,570,640,853,1280,1920],kod="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Go7=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],os0=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var $ad={pWZ:"current",GAR:"new"};var TU6={CLOSE:"close",a34:"openUrl",SUBSCRIBE:"subscribe"},Fw6={F4Z:"click",CLOSE:"close",ooJ:"hidden",SI2:"rollOut",VUR:"rollOver",aYJ:"shown"};uiU.prototype.Ne=function(){var Y=bT1(this,function(e){return e.type==="openUrl"&&e.url!=null});
return Y?Y.url:null};
var FYn={nC4:"anchored",DF:"branding",CHANNEL:"channel",XWq:"cta",d9F:"highlightText",Qb4:"label",PLAYLIST:"playlist",POPUP:"popup",HD6:"speech",SUBSCRIBE:"subscribe",dFq:"title",VIDEO:"video",nHJ:"website"},TK1={DF:"branding",rs4:"card",lDJ:"drawer",Yu6:"highlight",tW4:"marker",NMd:"promotion",TEXT:"text",ZU7:"widget"};g.m(Db,g.J);g.R=Db.prototype;g.R.addCueRange=function(Y,e,K,x,z){Y=new g.HU(Y,e,{id:K,namespace:"annotations_module"});x&&this.Sd.set(Y,x);z&&this.Vq.set(Y,z);this.context.W.B_([Y],1)};
g.R.au=function(){this.context.L.subscribe("resize",this.uB,this)};
g.R.w2=function(){return this.element};
g.R.rF=function(Y,e,K,x,z,O){if(this.CF)return!1;O&&(O.stopPropagation(),O.preventDefault());this.navigate(Y,K,x,z);return!1};
g.R.show=function(){};
g.R.hide=function(){};
g.R.destroy=function(){g.Rb(this.w2())};
g.R.uB=function(){};
g.R.navigate=function(Y,e,K,x){var z=this,O=qR(Y);if(O){var T=R9a(O,Y.target),E=function(){Y.K&&z.context.W.pauseVideo();var u=z.context.videoData.Fq||!1,b=g.Dk(O||"");u&&b&&(b.v||b.list)?z.context.W.Gw(b.v,e,b.list,!1):g.jR(O||"",T==="current"?"_top":void 0,e)};
T==="new"&&(E(),E=null);EG(this.context.logger,K,E,x);fnU(O)||(K=g.Ld(),x=e.itct,K&&x&&g.yd(K,g.od(x)))}};
g.R.KF=function(){this.Sd.clear();this.Vq.clear();g.J.prototype.KF.call(this)};
g.R.createElement=function(Y){Y=new g.d(Y);g.S(this,Y);return Y.element};g.m(XG6,Db);g.R=XG6.prototype;g.R.Rb=function(){this.xq&&sG(this,this.xq)};
g.R.isAvailable=function(){var Y;if(Y=!!this.cards.length)(Y=this.W.getRootNode())?(Y=g.Kh(Y),Y=173<Y.width&&173<Y.height):Y=!1;return Y};
g.R.uB=function(){var Y=this.isAvailable();g.x1(this.w2(),Y);g.s$(this.context.W.getRootNode(),g.aw.IV_DRAWER_ENABLED,Y);pU(this.W)};
g.R.destroy=function(){this.W.mp(!1);try{this.W.getRootNode().removeChild(this.Y)}catch(Y){}g.Ig(this.nF);g.Um(this.W2);this.g7&&this.g7.dispose();this.U&&this.U.dispose();Db.prototype.destroy.call(this)};
g.R.g3=function(){var Y=this;this.context.K.listen(g.TR("iv-drawer-close-button",this.Y),"click",this.Bi,this);this.context.K.listen(this.L,"touchend",function(){Y.pF.start()});
this.context.K.listen(this.L,"scroll",this.xS,this);this.context.L.subscribe("onHideControls",function(){Y.Yq=!0});
this.context.L.subscribe("onShowControls",function(){Y.Yq=!1});
this.context.L.subscribe("onVideoAreaChange",function(){Y.Yq=g.tA(Y.W.getRootNode(),"ytp-autohide")});
this.nF.push(g.yY("iv-button-shown",this.xT7,this));this.nF.push(g.yY("iv-button-hidden",this.nqZ,this));NU6(this)};
g.R.findLastIndex=function(Y){if(this.cards.length===0)return 0;var e=g.XA(this.cards,function(K){return Y.Pp.startMs>K.Pp.startMs||Y.Pp.startMs===K.Pp.startMs&&Y.Pp.timestamp>=K.Pp.timestamp?!0:!1});
return e===-1?0:e+1};
g.R.Bi=function(){if(this.X){EG(this.context.logger,OG(this).hF.close);var Y=g.Ld();Y&&this.S&&g.yd(Y,this.S);Ke(this)}};
g.R.xS=function(){g.s$(this.Y,"iv-drawer-scrolled",this.L.scrollTop>0)};
g.R.xT7=function(){var Y=g.Ld(),e=OG(this);e=e?e.ud:this.ud;Y&&e&&g.nd(Y,[e])};
g.R.nqZ=function(){var Y=g.Ld(),e=OG(this);e=e?e.ud:this.ud;Y&&e&&g.w1(Y,[e])};
g.R.vB=function(){var Y=OG(this);EG(this.context.logger,Y.hF.qq);var e=g.Ld();if(e&&Y)if(this.W.Z("web_infocards_teaser_show_logging_fix")){var K=[];Y.DD&&K.push(Y.DD);Y.ud&&K.push(Y.ud);K.length>0&&g.nd(e,K)}else g.nd(e,[Y.DD,Y.ud])};
g.R.I4R=function(){var Y=g.Ld(),e=OG(this);Y&&e&&g.w1(Y,[e.DD])};
g.R.oK=function(Y){var e=OG(this),K=g.Ld();this.K?Y?(Y=this.context.logger,EG(Y,e.hF.LH),Y.W.sendVideoStatsEngageEvent(4,void 0),K&&e.DD&&g.yd(K,e.DD)):(Y=this.context.logger,EG(Y,e.hF.LH),Y.W.sendVideoStatsEngageEvent(4,void 0),K&&e.ud&&g.yd(K,e.ud)):(Y=this.context.logger,EG(Y,e.hF.LH),Y.W.sendVideoStatsEngageEvent(4,void 0),K&&this.ud&&g.yd(K,this.ud))};g.m(Tq,Db);Tq.prototype.au=function(){Db.prototype.au.call(this);Ax6(this)};
Tq.prototype.show=function(){Db.prototype.show.call(this);var Y=g.Ld(),e=this.annotation.data;Y&&e&&(e=e.session_data)&&g.nd(Y,[g.od(e.itct)])};
Tq.prototype.hide=function(){Db.prototype.hide.call(this);var Y=g.Ld(),e=this.annotation.data;Y&&e&&(e=e.session_data)&&g.w1(Y,[g.od(e.itct)])};g.m(Fu,Tq);
Fu.prototype.show=function(){if(!this.isActive){Tq.prototype.show.call(this);if(!this.T){g.YI(this.w2(),"iv-branding");var Y=this.annotation.data;this.L=this.createElement({N:"img",v2:["branding-img","iv-click-target"],V:{"aria-label":"\ucc44\ub110 \uc6cc\ud130\ub9c8\ud06c",src:Y.image_url,width:Y.image_width,height:Y.image_height}});g.x1(this.L,!1);var e=this.createElement({N:"button",v2:["branding-img-container","ytp-button"]});e.appendChild(this.L);this.w2().appendChild(e);var K=this.annotation.Ne();K&&
tO(this,e,K,this.annotation.id,Y.session_data);this.context.W.Z("disable_branding_context")||iTM(this,Y);this.T=!0}g.x1(this.w2(),!0);this.isActive=!0;if(this.L){try{vTz(this,this.L)}catch(x){}g.YI(this.context.W.getRootNode(),"ytp-branding-shown");this.context.W.getRootNode().style.setProperty("--branding-image-width",this.L.getAttribute("width")+"px")}}};
Fu.prototype.hide=function(){this.isActive&&(Tq.prototype.hide.call(this),g.x1(this.w2(),!1),this.isActive=!1,g.Kw(this.context.W.getRootNode(),"ytp-branding-shown"))};
Fu.prototype.destroy=function(){this.K&&(this.K.dispose(),this.K=null);g.Kw(this.context.W.getRootNode(),"ytp-branding-shown");Tq.prototype.destroy.call(this)};g.m(SOx,Tq);g.R=SOx.prototype;g.R.show=function(){this.isActive||(Tq.prototype.show.call(this),this.C||(HTz(this),this.C=!0),g.x1(this.w2(),!0),g.Al(function(){g.Kw(this.w2(),"iv-promo-inactive")},100,this),this.w2().removeAttribute("aria-hidden"),this.isActive=!0,nT1(this),lna(this),daa(this,this.U))};
g.R.hide=function(){this.isActive&&(g.YI(this.w2(),"iv-promo-inactive"),this.isActive=!1,this.w2().setAttribute("aria-hidden","true"))};
g.R.rF=function(Y,e,K,x,z,O){return this.isCollapsed?!1:Tq.prototype.rF.call(this,Y,e,K,x,z,O)};
g.R.TF=function(Y){this.S=!0;Wwq(this,500,Y)};
g.R.ZS=function(){this.S=!1;qOL(this)};
g.R.gk=function(Y){Y.stopPropagation();this.hide()};
g.R.s1=function(Y){Y.stopPropagation();nT1(this);this.isCollapsed=!0;g.YI(this.w2(),"iv-promo-collapsed-no-delay");this.B.start()};
g.R.destroy=function(){this.B.dispose();Tq.prototype.destroy.call(this)};g.m(yxA,g.Ms);g.R=yxA.prototype;g.R.kC=function(Y,e){if(!uB0(this.player.D().playerStyle))return null;switch(Y){case "loadCustomAnnotationsXml":return(Y=g.IQ(e))&&eV6(this,Y),!0;case "removeCustomAnnotationById":return e&&this.K&&(h9x(this.K,e),pU(this.player)),!0}return null};
g.R.getOptions=function(){return uB0(this.player.D().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.R.JT=function(){var Y=this.player.D(),e=this.player.getVideoData(),K=Y.annotationsLoadPolicy||e.annotationsLoadPolicy;return e.Fq||this.player.isMutedByEmbedsMutedAutoplay()?!1:K===1&&!e.Ok||Y.Yq.get(e.videoId)||g.zv(e)||g.$0(e)?!0:!1};
g.R.jw=function(){if(this.X){var Y=this.player.GZ().getVideoContentRect(!0);g.en(this.X.element,Y.width,Y.height);g.Ib(this.X.element,Y.left,Y.top)}if(this.K){var e=this.player.ph();Y=this.K;e=e.width;g.s$(Y.Y,"iv-drawer-small",e<=426);g.s$(Y.Y,"iv-drawer-big",e>=1280)}};
g.R.YK=function(Y){Dad(this,Y.state);g.n(Y.state,2)&&(this.xo()&&this.ol()&&this.player.getPresentingPlayerType()!==2&&this.XM(!1),this.mp(!1))};
g.R.load=function(){function Y(T){var E=e.loadNumber;e.B=null;e.loaded&&e.loadNumber===E&&e.player.getVideoData().videoId===x&&(T=g.TN(T)&&T.responseXML?T.responseXML:null)&&(eV6(e,T),g.YI(e.player.getRootNode(),"iv-module-loaded"))}
var e=this;g.Ms.prototype.load.call(this);Dad(this,this.player.getPlayerStateObject());this.loadNumber++;var K=this.player.getVideoData(),x=K.videoId;g.n7()&&(Y=KYM(this,Y));var z={format:"XML",onFinish:Y,onError:function(){e.B=null},
urlParams:{}};K.isPharma&&(z.urlParams.pharma="1");z.method="POST";z.withCredentials=!0;var O=this.player.D().Yq.get(x);O&&xE1(z,O);O=O&&(O.Id||O.C1);if(!K.Mj||O)K.W2?tT1(this,K.W2,z):(this.T=function(){if(!e.S)e.onVideoDataChange(z);var T=e.player.getVideoData();(T==null?0:g.sN(T))&&!e.nF&&OJx(e,T)},this.player.addEventListener("videodatachange",this.T));
g.Yw(this.player,this.X.element,4);this.jw();(O=g.zv(K))&&$Ea(this,O);(O=g.$0(K))&&O.featuredChannel&&Esz(this,O.featuredChannel,O.annotationId||"branding",K.videoId||null,K.eventId||null);this.VX=g.TR("ytp-cards-button",this.player.getRootNode());g.sN(K)&&OJx(this,K)};
g.R.onVideoDataChange=function(Y){var e=this.player.getVideoData();e.W2&&tT1(this,e.W2,Y)};
g.R.unload=function(){this.player.l1("annotations_module");for(var Y=g.a(Object.keys(this.U)),e=Y.next();!e.done;e=Y.next())this.U[e.value].destroy();this.C=null;this.K&&(this.K.destroy(),this.K=null,pU(this.player));this.S=!1;this.B&&(this.B.abort(),this.B=null);this.nF=!1;this.U={};this.L.hide();g.Ms.prototype.unload.call(this);this.X.detach();this.T&&(this.player.removeEventListener("videodatachange",this.T),this.T=null)};
g.R.l8=function(Y){Y===this.player.getVideoData().videoId&&(this.loaded?sHA(this):this.load())};
g.R.xo=function(){var Y;return((Y=this.K)==null?void 0:Y.isAvailable())||this.nF};
g.R.ol=function(){return!!this.K&&this.K.X};
g.R.XM=function(Y,e,K){e=e===void 0?!1:e;this.xo();this.K&&(Y?K?eQ(this.K,K,e):eQ(this.K,"YOUTUBE_DRAWER_AUTO_OPEN",e):Ke(this.K))};
g.R.mp=function(Y,e){this.player.publish(Y?"cardsteasershow":"cardsteaserhide",e)};
g.R.KF=function(){this.player.D().Yq.unsubscribe("vast_info_card_add",this.l8,this);g.Kw(this.player.getRootNode(),g.aw.IV_DRAWER_OPEN);for(var Y=this.xq,e=g.g6,K=0,x=Y.length;K<x;K++)e.IP(Y[K]);this.xq.length=0;g.Ms.prototype.KF.call(this)};
g.R.createElement=function(Y){Y=new g.d(Y);g.S(this,Y);return Y.element};g.PA("annotations_module",yxA);g.PA("creatorendscreen",lpx);})(_yt_player);
