(function(g){var window=this;'use strict';var f6A=function(Y,e,K){g.C(function(x){Y.K=g.RE(e,K);g.aS(x)})},bP=function(Y){Y.isActive()||Y.start()},RVZ=function(Y,e){return e?Y.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},mE1=function(Y){return g.Uv(Y)||Y.Z("web_enable_caption_language_preference_stickiness")},XjM=function(Y,e){var K=new g.SC;
K.languageCode=Y.languageCode;K.languageName=Y.languageName;K.name=Y.name;K.displayName=Y.displayName;K.kind=Y.kind;K.isDefault=!1;K.K=Y.K;K.isTranslateable=Y.isTranslateable;K.vssId=Y.vssId;K.url=Y.url;K.translationLanguage=e;Y.xtags&&(K.xtags=Y.xtags);Y.captionId&&(K.captionId=Y.captionId);return K},a61=function(Y,e){var K,x,z;
return g.C(function(O){if(O.L==1)return K=Y+"|"+e,g.c(O,g.dg(),2);if(O.L!=3){x=O.K;if(!x)throw g.o1("gct");return g.c(O,g.$o(x),3)}z=O.K;return O.return(z.get("captions",K))})},UE1=function(Y,e,K){a61(Y,e).then(function(x){x&&K(x.trackData,new g.SC(x.metadata))})},PFA=function(Y){if(!QHA.test(Y))throw Error("'"+Y+"' is not a valid hex color");
Y.length==4&&(Y=Y.replace(hVn,"#$1$1$2$2$3$3"));Y=Y.toLowerCase();Y=parseInt(Y.slice(1),16);return[Y>>16,Y>>8&255,Y&255]},MW1=function(){var Y=void 0;
Y=Y===void 0?{}:Y;var e="suggest_correction"in g.wl7?g.wl7.suggest_correction:"Edit caption";e=e||"";var K={},x;for(x in Y){K={eH:K.eH};K.eH=x;var z=function(O){return function(){return String(Y[O.eH])}}(K);
e=e.replace(new RegExp("\\$\\{"+K.eH+"\\}","gi"),z);e=e.replace(new RegExp("\\$"+K.eH,"gi"),z)}return e},NKM=function(){return g.MT("yt-player-caption-display-settings")},kJ=function(){this.segments=[]},ZJL=function(Y,e){var K=g.Wz(Y.segments,e);
K>=0||K<0&&(-K-1)%2===1||(K=-K-1,K>0&&e-Y.segments[K-1]===1&&K<Y.segments.length&&Y.segments[K]-e===1?(g.U1(Y.segments,K),g.U1(Y.segments,K-1)):K>0&&e-Y.segments[K-1]===1?Y.segments[K-1]=e:K<Y.segments.length&&Y.segments[K]-e===1?Y.segments[K]=e:(g.iM(Y.segments,K,0,e),g.iM(Y.segments,K+1,0,e)))},pjz=function(Y,e,K,x,z,O){g.J.call(this);
this.policy=Y;this.player=e;this.nF=K;this.S=x;this.B=z;this.C=O;this.Y=new kJ;this.U=-1;this.X=this.L=this.K=null;this.xq=0;this.T=new g.S2(this.aj,1E3,this);this.events=new g.US(this);g.S(this,this.T);g.S(this,this.events);this.events.J(e,"SEEK_COMPLETE",this.UT);this.UT();this.aj()},cgA=function(Y){return Y.K&&Y.K.U?Y.K.U+Y.player.ES()<Y.player.getCurrentTime():!1},VWM=function(Y,e){if(Y.policy.yD&&Y.player.gR()){var K=g.uf(e,Y.policy,{});
K.set("pot",Y.player.gR());K=K.Ne()}else K=g.uf(e,Y.policy,{}).Ne();var x={format:"RAW",withCredentials:!0};if(Y.policy.fF){x.method="POST";var z=e.Y;z&&Object.keys(z).length>0?x.postBody=g.dD(z,g.Vw):x.postBody=(0,g.iV)([120,0])}Y.B&&(x.responseType="arraybuffer");var O=++Y.xq,T=(0,g.mJ)();Y.X=g.U_(K,x,3,100,-1,function(E){E.errorCode==="net.timeout"&&Y.player.Ii("capnt",{rn:O++})}).then(function(E){if(Y.policy.tP&&O%100===1){var u=(0,g.mJ)();
Y.player.Ii("caprsp",{rn:O,ms:u-T,kb:(E.xhr.responseText.length/1024).toFixed()})}a:{E=E.xhr;Y.qT();if(Y.L){var b=!(Y.B?E.response:E.responseText)||E.status>=400;if(u=g.Fvm(E)){E=g.uf(Y.L,Y.policy,{});Y.L.oP(E,u);VWM(Y,Y.L);break a}if(b)Y.player.Ii("capfail",{status:E.status});else{var k;g.eb("fcb_r",(0,g.mJ)(),((k=Y.player.getVideoData())==null?void 0:k.nF)||"");k=Y.L.zZ[0].d7;Y.S!=null&&Y.U!==k&&(u=Y.L.zZ[0],Y.B?Y.S(E.response,(u.startTime+Y.player.ES())*1E3):Y.S(E.responseText,(u.startTime+Y.player.ES())*
1E3),Y.U=k)}}Y.L=null;Y.X=null}}).uL(function(E){Y.L=null;
Y.X=null;var u;Y.player.Ii("capfail",{rn:O,status:(u=E.xhr)==null?void 0:u.status})});
Y.L=e;ZJL(Y.Y,Y.L.zZ[0].d7)},oU=function(Y,e){g.Z5.call(this,e);
this.K=Y;this.W=e;this.Y=null;this.U=!1;this.logger=new g.Xh("caps");this.T=g.KGR(this.W,this.K)},gsZ=function(Y,e){var K=[],x;
for(x in Y.K.K)if(Y.K.K.hasOwnProperty(x)){var z=Y.K.K[x];if(g.cA(z,e||null)){var O=z.info.id,T=O,E="."+O,u="",b="";if(z=z.info.captionTrack)O=z.languageCode,T=z.displayName,E=z.vssId,u=z.kind,b=z.id;else{z=O;var k=g.R0L.get(z);k==null&&(k=CFz[z]||CFz[z.replace(/-/g,"_")],g.R0L.set(z,k));z=k;T=z||T}K.push(new g.SC({id:x,languageCode:O,languageName:T,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:E,kind:u,captionId:b}))}}return K},Agn=function(Y,e){return e!=null&&e in Y.K.K?Y.K.K[e]:null},
vsU=function(Y,e,K){var x=[],z;
for(z in Y.K.K)if(Y.K.K.hasOwnProperty(z)){var O=Y.K.K[z];if(g.cA(O,K||null)){var T=O.info.captionTrack;T&&T.languageCode===e&&x.push(O)}}return x.length?x[0]:null},Gq=function(Y,e,K,x,z,O,T,E,u,b){var k=b.isInline()&&!0,G={};
Object.assign(G,e);Object.assign(G,Y.params);Object.assign(G,K);var B={};Object.assign(B,e.eI);Y.params.eI&&Object.assign(B,Y.params.eI);Object.assign(B,K.eI);k&&(G.windowOpacity=.6,B.backgroundOpacity=0);G.eI=B;var L=G.cZ===1,f=[{N:"span",j:"captions-text",V:{style:"word-wrap: normal; display: block;"}}],U,h,Z;(E=E.D4("caption_edit_on_hover")&&((U=b.getVideoData().getPlayerResponse())==null?void 0:(h=U.captions)==null?void 0:(Z=h.playerCaptionsTracklistRenderer)==null?void 0:Z.openTranscriptCommand))&&
f.unshift({N:"button",j:"caption-edit",V:{tabindex:"0","aria-label":MW1()},G:[{N:"svg",V:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},G:[{N:"path",V:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.d.call(this,{N:"div",j:"caption-window",V:{id:"caption-window-"+Y.id,dir:L?"rtl":"ltr",tabindex:"0",lang:G.lang},G:f});var N=
this;this.T=[];this.X6=!1;this.L=Y;this.Yq=this.fF=null;this.vn=O;this.ao=T;this.S=null;this.maxWidth=O*.96;this.maxHeight=T*.96;this.K=G;this.JR=K;this.xq=e;this.Y=this.w7("captions-text");this.hR=this.Y.style.getPropertyValue("box-decoration-break")!==""||this.Y.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.g7=rg6(x,z,O,T);this.jL=u;E&&(this.U=this.w7("caption-edit"),this.J(this.U,"click",function(){N.jL()}));
this.type=0;this.Sd=this.g7*jH0(B);this.bJ=k;Y=new g.WT(this.element,!0);g.S(this,Y);Y.subscribe("dragstart",this.qm,this);Y.subscribe("dragmove",this.Nm,this);Y.subscribe("dragend",this.dZ,this);this.TZ=this.Vq=this.CF=this.uJ=0;Y="";this.K.windowOpacity&&(Y=PFA(this.K.windowColor),Y="rgba("+Y[0]+","+Y[1]+","+Y[2]+","+this.K.windowOpacity+")");e={"background-color":Y,display:this.K.isVisible===!1?"none":"","text-align":iJn[this.K.textAlign]};this.hR&&(e["border-radius"]=Y?this.Sd/8+"px":"");(this.X=
this.L.params.cZ===2||this.L.params.cZ===3)&&Jg1(this,this.element);g.ln(this.element,e);if(k){var V;(V=this.element.parentElement)==null||V.style.setProperty("--caption-window-color",Y)}switch(this.K.eU){case 0:case 1:case 2:g.YI(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.YI(this.element,"ytp-caption-window-bottom")}},Jg1=function(Y,e){var K="vertical-rl";
Y.K.R7===1&&(K="vertical-lr");g.TX&&(K=K==="vertical-lr"?"tb-lr":"tb-rl");g.ln(e,"-o-writing-mode",K);g.ln(e,"-webkit-writing-mode",K);g.ln(e,"writing-mode",K);g.ln(e,"text-orientation","upright");g.YI(e,"ytp-vertical-caption");Y.L.params.cZ===3&&(g.ln(e,"text-orientation",""),g.ln(e,"transform","rotate(180deg)"))},jH0=function(Y){var e=1+.25*(Y.fontSizeIncrement||0);
if(Y.offset===0||Y.offset===2)e*=.8;return e},SWA=function(Y,e){var K={},x=e.background?e.background:Y.K.eI.background;
if(e.backgroundOpacity!=null||e.background){var z=e.backgroundOpacity!=null?e.backgroundOpacity:Y.K.eI.backgroundOpacity;x=PFA(x);K.background="rgba("+x[0]+","+x[1]+","+x[2]+","+z+")";Y.hR&&(K["box-decoration-break"]="clone",K["border-radius"]=Y.Sd/8+"px")}if(e.fontSizeIncrement!=null||e.offset!=null)K["font-size"]=Y.g7*jH0(e)+"px";x=1;z=e.color||Y.K.eI.color;if(e.color||e.textOpacity!=null)z=PFA(z),x=e.textOpacity==null?Y.K.eI.textOpacity:e.textOpacity,z="rgba("+z[0]+","+z[1]+","+z[2]+","+x+")",
K.color=z,K.fill=z;var O=e.charEdgeStyle;O===0&&(O=void 0);if(O){z="rgba(34, 34, 34, "+x+")";var T="rgba(204, 204, 204, "+x+")";e.Qv&&(T=z=e.Qv);var E=Y.g7/16/2,u=Math.max(E,1),b=Math.max(2*E,1),k=Math.max(3*E,1),G=Math.max(5*E,1);x=[];switch(O){case 4:for(;k<=G;k+=E)x.push(b+"px "+b+"px "+k+"px "+z);break;case 1:b=window.devicePixelRatio>=2?.5:1;for(O=u;O<=k;O+=b)x.push(O+"px "+O+"px "+z);break;case 2:x.push(u+"px "+u+"px "+T);x.push("-"+u+"px -"+u+"px "+z);break;case 3:for(k=0;k<5;k++)x.push("0 0 "+
b+"px "+z)}K["text-shadow"]=x.join(", ")}z="";switch(e.fontFamily){case 1:z='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:z='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:z='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:z='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:z='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:z=g.jL()?
'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:z='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}z&&(K["font-family"]=z);z=e.offset;z==null&&(z=Y.K.eI.offset);switch(z){case 0:K["vertical-align"]="sub";break;case 2:K["vertical-align"]="super"}e.fontFamily===7&&(K["font-variant"]="small-caps");e.bold&&(K["font-weight"]="bold");e.italic&&(K["font-style"]="italic");e.underline&&(K["text-decoration"]=
"underline");e.Q6&&(K.visibility="hidden");e.AE===1&&Y.X&&(K["text-combine-upright"]="all",K["text-orientation"]="mixed",z=g.MY||g.bR,Y.L.params.cZ===3?K.transform=z?"rotate(90deg)":"rotate(180deg)":z&&(K.transform="rotate(-90deg)"));if(e.textEmphasis===1||e.textEmphasis===2||e.textEmphasis===3||e.textEmphasis===4||e.textEmphasis===5)if(g.MY)K["font-weight"]="bold";else switch(K["text-emphasis-style"]="filled circle",K["text-emphasis-color"]="currentcolor",K["webkit-text-emphasis"]="filled circle",
e.textEmphasis){case 4:case 3:K["text-emphasis-position"]="under left";K["webkit-text-emphasis-position"]="under left";break;case 5:case 2:K["text-emphasis-position"]="over right",K["webkit-text-emphasis-position"]="over right"}return K},Ba=function(Y){Y=Y.split("px");
return Y.length>0?(Y=Number(Y[0]))?Y:0:0},WYA=function(Y){Y.S=g.ob("SPAN");
g.ln(Y.S,{display:"block"});g.YI(Y.S,"caption-visual-line");Y.Y.appendChild(Y.S)},HJz=function(Y,e){var K=g.ob("SPAN");
g.ln(K,{display:"inline-block","white-space":"pre-wrap"});g.ln(K,SWA(Y,e));K.classList.add("ytp-caption-segment");Y.S.appendChild(K);K.previousElementSibling&&(g.ln(K.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.ln(K,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return K},l6n=function(Y,e,K){Y.X6=Y.X6||!!K;
var x={};Object.assign(x,Y.K.eI);Object.assign(x,K||e.K);Object.assign(x,Y.JR.eI);(K=!Y.S)&&WYA(Y);for(var z=Y.fF&&Y.Yq&&g.GK(x,Y.Yq)?Y.fF:HJz(Y,x),O=typeof e.text==="string",T=O?e.text.split("\n"):[e.text],E=0;E<T.length;E++){var u=E>0||!e.append,b=T[E];u&&!K?(WYA(Y),z=HJz(Y,x)):u&&K&&(K=!1);b&&(z.appendChild(O?g.GR(b):b),O||b.tagName!=="RUBY"||b.childElementCount!==4||g.MY||!g.q_(b.children[2],"text-emphasis")||(u=Y.X?"padding-right":"padding-top",g.q_(b.children[2],"text-emphasis-position")&&(u=
Y.X?"padding-left":"padding-bottom"),g.Ej?g.ln(z,u,"1em"):g.ln(z,u,"0.5em")))}Y.Yq=x;Y.fF=z;Y.T.push(e)},rg6=function(Y,e,K,x){var z=e/360*16;
e>=Y&&(Y=640,x>K*1.3&&(Y=480),z=K/Y*16);return z},qW6=function(){this.X=this.time=this.mode=this.L=0;
this.Y=new dEx(this);this.B=new dEx(this);this.K=[];this.clear()},wj7=function(Y,e,K){if(Y===255&&e===255||!Y&&!e)return{Dj:Y,
Ob:e,result:0};Y=nsP[Y];e=nsP[e];if(Y&128){var x;if(x=!(e&128))x=e,x=K.c_()&&K.Ob===x;if(x)return{Dj:Y,Ob:e,result:1}}else if(e&128&&1<=Y&&Y<=31)return{Dj:Y,Ob:e,result:2};return{Dj:Y,Ob:e,result:3}},I6z=function(Y,e,K,x){e===255&&K===255||!e&&!K?(++Y.X===45&&Y.reset(),Y.Y.L.clear(),Y.B.L.clear()):(Y.X=0,yg1(Y.Y,e,K,x))},DEM=function(Y,e){Y.K.sort(function(z,O){var T=z.time-O.time;
return T===0?z.order-O.order:T});
for(var K=g.a(Y.K),x=K.next();!x.done;x=K.next())x=x.value,Y.time=x.time,x.type===0?I6z(Y,x.bF,x.aB,e):x.type===1&&Y.L&496&&yg1(Y.B,x.bF,x.aB,e);Y.K.length=0},Le=function(){this.type=0},fe=function(){this.state=this.Ob=this.Dj=0},tW1=function(){this.timestamp=this.K=0},RU=function(Y){this.B=Y;
this.X=[];this.K=this.L=this.row=0;this.style=new Le;for(Y=this.Y=0;Y<=15;Y++){this.X[Y]=[];for(var e=0;e<=32;e++)this.X[Y][e]=new tW1}},mW=function(Y,e){if(Y.style.type===3){for(var K=0,x=0,z=Y.B.time+0,O="",T="",E=z,u=1;u<=15;++u){for(var b=!1,k=x?x:1;k<=32;++k){var G=Y.X[u][k];
if(G.K!==0){K===0&&(K=u,x=k);b=String.fromCharCode(G.K);var B=G.timestamp;B<z&&(z=B);G.timestamp=E;T&&(O+=T,T="");O+=b;b=!0}if((G.K===0||k===32)&&b){T="\n";break}else if(x&&!b)break}if(K&&!b)break}O&&e.Y(K,x,z,E,O)}else for(x=K=0,O=z=Y.B.time+0,T=1;T<=15;++T)for(E="",u=1;u<=32;++u)if(k=Y.X[T][u],G=k.K,G!==0&&(K===0&&(K=T,x=u),b=String.fromCharCode(G),B=k.timestamp,B<=z&&(z=B),E+=b,k.reset()),u===32||G===0)E&&e.Y(K,x,z,O,E),z=O,E="",x=K=0},sfx=function(Y,e){switch(Y){case 0:return Ys7[(e&127)-32];
case 1:return eTA[e&15];case 2:return KtM[e&31];case 3:return xjU[e&31]}return 0},Xu=function(Y){return Y.X[Y.row][Y.L]},aU=function(Y,e,K){e>=2&&Y.L>1&&(--Y.L,Xu(Y).K=0);
var x=Xu(Y);x.timestamp=Y.B.time+0;x.K=sfx(e,K);Y.L<32&&Y.L++},zTU=function(Y,e,K,x){for(var z=0;z<x;z++)for(var O=0;O<=32;O++){var T=Y.X[e+z][O],E=Y.X[K+z][O];
T.K=E.K;T.timestamp=E.timestamp}},UG=function(Y,e,K){for(var x=0;x<K;x++)for(var z=0;z<=32;z++)Y.X[e+x][z].reset()},$jz=function(Y){Y.row=Y.K>0?Y.K:1;
Y.L=1;UG(Y,0,15)},OOa=function(Y){this.X=Y;
this.B=0;this.style=new Le;this.U=new RU(this.X);this.T=new RU(this.X);this.text=new RU(this.X);this.L=this.U;this.Y=this.T;this.K=this.L},Tix=function(Y,e,K){var x=Y.L,z=!1;
switch(Y.style.get()){case 4:case 1:case 2:Y.style.get()===4&&x.K>0||(mW(x,K),$jz(Y.L),$jz(Y.Y),x.row=15,x.K=e,z=!0)}Y.style.set(3);Y.K=x;Y.K.style=Y.style;Y.X.mode=1<<x.Y;z?x.L=1:x.K!==e&&(x.K>e?(mW(x,K),UG(x,x.row-x.K,e)):x.row<e&&(e=x.K),x.K=e)},FtA=function(Y){Y.style.set(1);
Y.K=Y.Y;Y.K.K=0;Y.K.style=Y.style;Y.X.mode=1<<Y.K.Y},Er0=function(Y){Y.style.set(4);
Y.K=Y.text;Y.K.style=Y.style;Y.X.mode=1<<Y.K.Y},dEx=function(Y){this.K=Y;
this.B=0;this.X=new OOa(this.K);this.U=new OOa(this.K);this.L=new fe;this.Y=this.X},yg1=function(Y,e,K,x){Y.L.update();
e=wj7(e,K,Y.L);switch(e.result){case 0:return;case 1:case 2:return}var z=e.Dj;K=e.Ob;if(32<=z||!z)Y.K.mode&Y.K.L&&(e=z,e&128&&(e=127),K&128&&(K=127),Y=Y.Y.K,e&96&&aU(Y,0,e),K&96&&aU(Y,0,K),e!==0&&K!==0&&Y.style.type===3&&mW(Y,x));else if(z&16)a:if(!Y.L.matches(z,K)&&(e=Y.L,e.Dj=z,e.Ob=K,e.state=2,e=z&8?Y.U:Y.X,Y.Y=e,Y.K.mode=1<<(Y.B<<2)+(e.B<<1)+(e.style.type===4?1:0),(Y.K.mode|1<<(Y.B<<2)+(e.B<<1)+(e.style.type!==4?1:0))&Y.K.L))if(K&64){x=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(z&7)<<1|K>>5&1];
Y=K&16?((K&14)>>1)*4:0;K=e.K;switch(e.style.get()){case 4:x=K.row;break;case 3:if(x!==K.row){if(x<K.K&&(x=K.K,x===K.row))break;var O=1+K.row-K.K,T=1+x-K.K;zTU(K,T,O,K.K);e=O;z=K.K;T<O?(O=T+z-O,O>0&&(e+=O,z-=O)):(O=O+z-T,O>0&&(z-=O));UG(K,e,z)}}K.row=x;K.L=Y+1}else switch(z&7){case 1:switch(K&112){case 32:aU(e.K,0,32);break a;case 48:K===57?(x=e.K,Xu(x).K=0,x.L<32&&x.L++):aU(e.K,1,K&15)}break;case 2:K&32&&aU(e.K,2,K&31);break;case 3:K&32&&aU(e.K,3,K&31);break;case 4:case 5:if(32<=K&&K<=47)switch(K){case 32:FtA(e);
break;case 33:x=e.K;x.L>1&&(--x.L,Xu(x).K=0);break;case 36:x=e.K;e=Xu(x);for(Y=0;Y<=15;Y++)for(K=0;K<=32;K++)if(x.X[Y][K]===e){for(;K<=32;K++)x.X[Y][K].reset();break}break;case 37:Tix(e,2,x);break;case 38:Tix(e,3,x);break;case 39:Tix(e,4,x);break;case 40:aU(e.K,0,32);break;case 41:e.style.set(2);e.K=e.L;e.K.K=0;e.K.style=e.style;e.X.mode=1<<e.K.Y;break;case 42:x=e.text;x.K=15;x.style.set(4);$jz(x);Er0(e);break;case 43:Er0(e);break;case 44:Y=e.L;switch(e.style.get()){case 1:case 2:case 3:mW(Y,x)}UG(Y,
0,15);break;case 45:b:{Y=e.K;switch(e.style.get()){default:case 2:case 1:break b;case 4:if(Y.row<15){++Y.row;Y.L=1;break b}break;case 3:}Y.K<2&&(Y.K=2,Y.row<Y.K&&(Y.row=Y.K));e=Y.row-Y.K+1;mW(Y,x);zTU(Y,e,e+1,Y.K-1);UG(Y,Y.row,1)}break;case 46:UG(e.Y,0,15);break;case 47:mW(e.L,x),e.Y.updateTime(e.X.time+0),x=e.Y,e.Y=e.L,e.L=x,FtA(e)}break;case 7:switch(K){case 33:case 34:case 35:x=e.K,(x.L+=K&3)>32&&(x.L=32)}}},u$d=function(){},Qv=function(Y,e,K,x,z,O,T){O=O===void 0?!1:O;
T=T===void 0?null:T;g.HU.call(this,Y,Y+e,{priority:K,namespace:"captions"});this.windowId=x;this.text=z;this.append=O;this.K=T},k$P=function(Y,e,K,x,z,O,T){var E=O[0],u=T[E.getAttribute("p")];
if(u.hv===1){var b=O[1],k=O[2];O=O[3];E.getAttribute("t");b.getAttribute("t");k.getAttribute("t");O.getAttribute("t");E.getAttribute("p");b.getAttribute("p");O.getAttribute("p");T=T[k.getAttribute("p")];E=bOn(E.textContent,b.textContent,k.textContent,O.textContent,T);return new Qv(Y,e,z,K,E,x,u)}switch(u.hv){case 9:case 10:u.textEmphasis=1;break;case 11:u.textEmphasis=2;break;case 12:u.textEmphasis=3;break;case 13:u.textEmphasis=4;break;case 14:u.textEmphasis=5}return new Qv(Y,e,z,K,E.textContent||
"",x,u)},bOn=function(Y,e,K,x,z){var O=g.jL(),T=O?g.ob("DIV"):g.ob("RUBY"),E=g.ob("SPAN");
E.textContent=Y;T.appendChild(E);Y=O?g.ob("DIV"):g.ob("RP");Y.textContent=e;T.appendChild(Y);e=O?g.ob("DIV"):g.ob("RT");e.textContent=K;T.appendChild(e);K=z.hv;if(K===10||K===11||K===12||K===13||K===14)if(g.ln(e,"text-emphasis-style","filled circle"),g.ln(e,"text-emphasis-color","currentcolor"),g.ln(e,"webkit-text-emphasis","filled circle"),z.hv===11||z.hv===13)g.ln(e,"webkit-text-emphasis-position","under left"),g.ln(e,"text-emphasis-position","under left");K=!0;if(z.hv===4||z.hv===7||z.hv===12||
z.hv===14)g.ln(T,"ruby-position","over"),g.ln(T,"-webkit-ruby-position","before");else if(z.hv===5||z.hv===6||z.hv===11||z.hv===13)g.ln(T,"ruby-position","under"),g.ln(T,"-webkit-ruby-position","after"),K=!1;z=O?g.ob("DIV"):g.ob("RP");z.textContent=x;T.appendChild(z);O&&(x=K,g.ln(T,{display:"inline-block",position:"relative"}),O=T.firstElementChild.nextElementSibling,g.ln(O,"display","none"),O=O.nextElementSibling,g.ln(O,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.ln(T.lastElementChild,"display","none"),x?(g.ln(T,"padding-top","0.6em"),g.ln(O,"top","0")):(g.ln(T,"padding-bottom","0.6em"),g.ln(O,"bottom","0")));return T},h2=function(){g.J.apply(this,arguments)},Pa=function(Y,e,K,x,z){g.HU.call(this,Y,Y+e,{priority:K,
namespace:"captions"});this.id=x;this.params=z;this.K=[]},ord=function(Y){var e="_"+MK++;
return new Pa(0,0x8000000000000,0,e,Y)},NK=function(Y){h2.call(this);
this.Y=Y;this.pens={};this.S={};this.C={};this.B="_"+MK++;this.T={};this.L=this.K=null;this.U=!0},Zj=function(Y,e){Y=Y.getAttribute(e);
if(Y!=null)return Number(Y)},pe=function(Y,e){Y=Y.getAttribute(e);
if(Y!=null)return Y==="1"},ca=function(Y,e){Y=Zj(Y,e);
return Y!==void 0?Y:null},Ce=function(Y,e){Y=Y.getAttribute(e);
if(Y!=null)return Vv.test(Y),Y},G$U=function(Y,e){var K={},x=e.getAttribute("ws");
Object.assign(K,x?Y.C[x]:Y.Y);Y=ca(e,"mh");Y!=null&&(K.sL=Y);Y=ca(e,"ju");Y!=null&&(K.textAlign=Y);Y=ca(e,"pd");Y!=null&&(K.cZ=Y);Y=ca(e,"sd");Y!=null&&(K.R7=Y);Y=Ce(e,"wfc");Y!=null&&(K.windowColor=Y);e=Zj(e,"wfo");e!==void 0&&(K.windowOpacity=e/255);return K},Bid=function(Y,e){var K={},x=e.getAttribute("wp");
x&&Object.assign(K,Y.S[x]);Y=ca(e,"ap");Y!=null&&(K.eU=Y);Y=Zj(e,"cc");Y!=null&&(K.im=Y);Y=Zj(e,"ah");Y!=null&&(K.N9=Y);Y=Zj(e,"rc");Y!=null&&(K.hx=Y);e=Zj(e,"av");e!=null&&(K.xH=e);return K},Lt1=function(Y,e,K,x){var z={};
Object.assign(z,Bid(Y,e));Object.assign(z,G$U(Y,e));x?g.GK(z,Y.Y)?(x=Y.B,z=Y.Y):x="_"+MK++:x=e.getAttribute("id")||"_"+MK++;Y=Zj(e,"t")+K;e=Zj(e,"d")||0x8000000000000;if(z.cZ===2||z.cZ===3)K=z.hx,z.hx=z.im,z.im=K;return new Pa(Y,e,0,x,z)},gu=function(Y){h2.call(this);
this.U=Y;this.K=new Map;this.Y=new Map;this.B=new Map;this.L=new Map},A2=function(Y){Y=g.JQ(Math.round(Y),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-Y.length)+Y},fXx=function(Y,e,K,x,z){x===0&&(x=0x8000000000000);
var O={};e.wpWinPosId&&Object.assign(O,Y.Y.get(e.wpWinPosId));e.wsWinStyleId&&Object.assign(O,Y.B.get(e.wsWinStyleId));Y=e.rcRowCount;Y!==void 0&&(O.hx=Y);e=e.ccColCount;e!==void 0&&(O.im=e);if(O.cZ===2||O.cZ===3)e=O.hx,O.hx=O.im,O.im=e;return new Pa(K,x,0,z,O)},va=function(Y,e,K){g.Z5.call(this,Y);
this.videoData=e;this.audioTrack=K;this.B=e.QR},ru=function(Y,e,K,x,z,O,T,E,u,b){Gq.call(this,Y,e,K,x,z,O,T,E,u,b);
this.type=1},jQ=function(Y,e,K){this.trackData=Y;
this.U=K;this.version=this.B=this.X=this.byteOffset=0;this.L=[];this.K=new DataView(this.trackData)},iP=function(Y){var e=Y.byteOffset;
Y.byteOffset+=1;return Y.K.getUint8(e)},J2=function(Y){var e=Y.byteOffset;
Y.byteOffset+=4;return Y.K.getUint32(e)},SQ=function(Y,e){h2.call(this);
this.L=Y;this.Y=e;this.track=this.Y.languageName==="CC3"?4:0;this.K=new qW6;this.K.L=1<<this.track},mja=function(Y){if(typeof Y==="string")return!1;
Y=new jQ(Y,8,0);return RTA(Y)},RTA=function(Y){if(!(Y.byteOffset<Y.K.byteLength)||J2(Y)!==1380139777)return!1;
Y.version=iP(Y);if(Y.version>1)return!1;iP(Y);iP(Y);iP(Y);return!0},Wa=function(Y,e,K,x,z,O,T,E,u,b){Gq.call(this,Y,e,K,x,z,O,T,E,u,b);
var k=this;this.type=2;this.LF=[];this.nF=this.C=this.W2=0;this.pF=NaN;this.x3=0;this.sS=null;this.Iq=new g.S2(this.ow,433,this);this.U&&(b.createClientVe(this.U,this,167342),this.J(this.U,"click",function(){b.logClick(k.U)}),Y=new g.WT(this.element,!0),g.S(this,Y),Y.subscribe("hoverstart",function(){b.logVisibility(k.U,!0)},this));
g.YI(this.element,"ytp-caption-window-rollup");g.S(this,this.Iq);g.ln(this.element,"overflow","hidden")},XCZ=function(Y,e){if(!e)return"";
Y.X&&Y.L.params.R7!==1&&(e*=-1);return"translate"+(Y.X?"X":"Y")+"("+e+"px)"},aXn=function(Y){Y.LF=Array.from(Y.element.getElementsByClassName("caption-visual-line"));
for(var e=Y.L.params.hx,K=0,x=0,z=Y.LF.length-1;K<e&&z>-1;){var O=Y.LF[z];x+=Y.X?O.offsetWidth:O.offsetHeight;K++;z--}Y.C=x;e=Math;K=e.max;isNaN(Y.pF)&&((x=Y.K.im)?(z=g.ob("SPAN"),g.X2(z,"\u2013".repeat(x)),g.ln(z,SWA(Y,Y.K.eI)),Y.Y.appendChild(z),Y.pF=z.offsetWidth,Y.Y.removeChild(z)):Y.pF=0);x=Y.Y;Y.nF=K.call(e,Y.pF,Y.x3,(Y.X?x.offsetHeight:x.offsetWidth)+1)},Uj1=function(Y,e){aXn(Y);
var K=Y.LF.reduce(function(O,T){return(Y.X?T.offsetWidth:T.offsetHeight)+O},0);
K=Y.C-K;if(K!==Y.W2){var x=K>0&&Y.W2===0,z=K<Y.W2;e||isNaN(K)||x||!z||(g.YI(Y.element,"ytp-rollup-mode"),Y.J(Y.element,"transitionend",Y.ow));g.ln(Y.Y,"transform",XCZ(Y,K));Y.W2=K}aXn(Y)},Qfq=function(Y,e,K,x){var z=this;
this.W=Y;this.X=e;this.logger=K;this.qn=x;this.kJ=[];this.UI=[];this.K=null;this.xJ={fg2:function(){return z.K},
O5:function(){return z.kJ}};
Y=g.ta(this.W.D().experiments,"html5_override_micro_discontinuities_threshold_ms");this.L=Y>0?Y:10},MS7=function(Y,e){Y.K=function(K,x){if(K.info.Y){var z=K;
if(Y.UI.length>0){for(z=Y.UI.shift();Y.UI.length>0;)z=g.hC(z,Y.UI.shift());z=g.hC(z,K)}if(z){K=z;try{var O=g.PZ(K)*1E3}catch(b){O=K.info.startTime*1E3}try{var T=g.t7A(K)*1E3}catch(b){T=K.info.duration*1E3}if(O<0||T<0)O<0&&(O=K.info.startTime*1E3),T<0&&(T=K.info.duration*1E3);K.info.startTime=O/1E3;K.info.B=O/1E3;K.info.duration=T/1E3;K.info.S=T/1E3;O=Y.vH(z);T=O.d7;O={formatId:O.formatId,startTimeMs:O.startTimeMs,durationMs:O.durationMs,Kz:T,bd:T};T=hTZ(Y.kJ,O.startTimeMs);var E=(K=T>=0?Y.kJ[T]:null)?
K.startTimeMs+K.durationMs:0,u=O.startTimeMs+O.durationMs;!K||O.startTimeMs-E>Y.L?Y.kJ.splice(T+1,0,O):(K.durationMs=Math.max(E,u)-K.startTimeMs,K.bd=Math.max(K.bd,O.bd));x(Y.kJ);x=g.Qz(z);PCx(Y.X,x.buffer.slice(x.byteOffset,x.byteLength+x.byteOffset),e,z.info.B)}else Y.logger.K(350058965,"Empty slice")}else Y.UI.push(K)};
Y.W.addEventListener("sabrCaptionsDataLoaded",Y.K)},hTZ=function(Y,e){Y=g.Wz(Y,{startTimeMs:e},function(K,x){return K.startTimeMs-x.startTimeMs});
return Y>=0?Y:-Y-2},Ha=function(Y,e){g.Z5.call(this,e);
this.K=Y;this.W=e;this.logger=new g.Xh("caps");this.Y=this.U=null;this.T=new Qfq(this.W,this,this.logger,this.K.qn)},PCx=function(Y,e,K,x){Y.logger.debug(function(){return"SABR captions data received for "+x});
Y.U?Y.Y==null?Y.logger.K(350058965,"Null loaded track meta data at captions data received"):K.pk(e,Y.Y,x*1E3):Y.logger.K(350058965,"Null Representation at captions data received")},NiZ=function(Y,e){var K=[],x;
for(x in Y.K.K)if(Y.K.K.hasOwnProperty(x)){var z=Y.K.K[x];if(g.cA(z,e||null)){var O=z.info.id,T=O,E="."+O,u="",b="";if(z=z.info.captionTrack)O=z.languageCode,T=z.displayName,E=z.vssId,u=z.kind,b=z.id;K.push(new g.SC({id:x,languageCode:O,languageName:T,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:E,kind:u,captionId:b}))}}return K},ZOq=function(Y,e,K){var x=[],z;
for(z in Y.K.K)if(Y.K.K.hasOwnProperty(z)){var O=Y.K.K[z];if(g.cA(O,K||null)){var T=O.info.captionTrack;T&&T.languageCode===e&&x.push(O)}}return x.length?x[0]:null},pCP=function(Y,e){if(!g.D6m(Y)||Y.K!=null&&g.KGR(e,Y.K)&&Y.K.K.rawcc!=null)return!1;
e=!!Y.K&&Y.K.isManifestless&&Object.values(Y.K.K).some(function(K){return g.cA(K,"386")});
Y=!!Y.K&&!Y.K.isManifestless&&g.kwp(Y.K);return e||Y},cLL=function(){h2.call(this)},CC7=function(Y){var e=VSA.length;
if(Y.byteLength<e)return!1;Y=new Uint8Array(Y,0,e);for(var K=0;K<e;K++)if(VSA[K]!==Y[K])return!1;return!0},grn=function(Y,e,K,x,z,O,T,E,u){switch(T.tagName){case "b":E.bold=!0;
break;case "i":E.italic=!0;break;case "u":E.underline=!0}for(var b=0;b<T.childNodes.length;b++){var k=T.childNodes[b];if(k.nodeType===3)k=new Qv(e,K,x,z.id,k.nodeValue,O||b>0,g.kM(E)?void 0:E),u.push(k),z.K.push(k);else{var G={};Object.assign(G,E);grn(Y,e,K,x,z,!0,k,G,u)}}},ALn=function(Y){var e=Y.split(":");
Y=0;e=g.a(e);for(var K=e.next();!K.done;K=e.next())Y=Y*60+Number(K.value);return Y*1E3},vrZ=function(Y,e,K,x){x=Object.assign({sL:0},x);
return new Pa(Y,e,K,"_"+MK++,x)},lP=function(Y,e){g.J.call(this);
this.W=Y;this.ai=e;this.K=null;this.L=this.W.Ud();this.logger=new g.Xh("caps")},jf1=function(Y,e,K){if(typeof e==="string"||mja(e))return[{trackData:e,
KH:K}];if(typeof e==="string"&&e.substring(0,6)==="WEBVTT"||typeof e!=="string"&&CC7(e))return[{trackData:e,KH:K}];var x=new DataView(e);if(x.byteLength<=8||x.getUint32(4)!==1718909296)return[];var z=g.eZR(x);if(Y.L&&z){var O=g.q98(z),T=g.npO(z);z=z.EE;O&&z&&Y.L.Fj(z,O,T)}Y=g.UJ(x,1835295092);if(!Y||!Y.length||!Y[0].size)return[];O=[];for(T=0;T<Y.length;T++)z=Y[T],z=new Uint8Array(e,z.dataOffset,z.size-(z.dataOffset-z.offset)),z=g.km(z),O.push({trackData:z,KH:K+T*1E3});rL1(x,O,K);return O=O.filter(function(E){return!!E.trackData})},
rL1=function(Y,e,K){var x=g.oM(Y,0,1836476516),z=9E4;
x&&(z=g.G5(x)||9E4);x=0;for(var O=g.UJ(Y,1836019558),T=0;T<O.length;T++){var E=O[T];T<e.length&&(E=g.oM(Y,E.dataOffset,1953653094))&&(E=g.oM(Y,E.dataOffset,1952867444))&&(E=g.Xt(E)/z*1E3,T===0&&(x=E),e[T].KH=E-x+K||K*T*1E3)}},iOq=function(Y,e,K){Y.K||(Y.K=new cLL);
Y=Y.K.X(e,K);Math.random()<.01&&g.P1(Error("Deprecated subtitles format in web player: WebVTT"));return Y},JL1=function(Y){var e={};
if(Y=g.lp(Y))e.lang=Y,g.Mq7.test(Y)&&(e.cZ=1);return e},HOd=function(Y){g.Ms.call(this,Y);
var e=this;this.W=Y;this.fF=[];this.LF={};this.Sd={};this.S=!1;this.Y="NONE";this.K=this.C=this.nF=this.g7=this.uJ=null;this.Iq={j1:function(){e.j1()},
pk:function(O,T,E,u){e.pk(O,T,E,u)}};
this.L=null;this.ai=this.W.D();this.videoData=this.W.getVideoData();this.CF=this.W.GZ();this.X={eI:{}};this.U={eI:{}};g.fC(this.videoData)?this.Y="OFFLINE":pCP(this.videoData,this.W)?this.Y="SABR_LIVE":g.xMc(this.videoData,this.W)?this.Y="LIVE":this.videoData.captionTracks.length?this.Y="INNERTUBE":this.videoData.Eo&&(this.Y="TTS");this.Vq=this.ai.controlsType==="3";this.TZ=new lP(this.W,this.ai);this.X6=new g.US(this);this.T=new g.d({N:"div",j:"ytp-caption-window-container",V:{id:"ytp-caption-window-container"}});
this.xq={top:0,right:0,bottom:0,left:0,width:1,height:1};var K=null,x=g.pw("yt-html5-player-modules::subtitlesModuleData");x&&(K=new g.Xo(x));this.storage=K;var z;this.bJ=!((z=Y.uq())==null||!z.Xn());this.B=Ssz(this);this.pF=!this.B&&this.Vq&&this.bJ&&(this.Y==="LIVE"||this.Y==="SABR_LIVE");g.S(this,this.TZ);this.B?this.W2=this.Yq=null:(this.Yq=new g.JA(this.e5,void 0,this),g.S(this,this.Yq),this.W2=new g.S2(this.tIF,2E3,this),g.S(this,this.W2));g.S(this,this.X6);g.Yw(this.player,this.T.element,4);
g.S(this,this.T);this.B||this.X6.J(Y,"resize",this.Tn);(this.x3=g.Ov(this.ai)&&!g.uD()&&!this.W.isFullscreen()&&!this.B&&!this.pF)&&this.X6.J(Y,"resize",this.g3d);this.X6.J(Y,"onPlaybackAudioChange",this.DTq);this.X6.J(Y,g.d2("captions"),function(O){e.onCueRangeEnter(O)});
this.X6.J(Y,g.qt("captions"),function(O){e.onCueRangeExit(O)});
Wtd(this,NKM()||{});this.player.IH("onCaptionsModuleAvailable")},qs6=function(Y){if(Y.ai.Gi===1||Y.videoData.fM===1||g.w7(Y.videoData,"yt:cc")==="alwayson")return!0;
if(Y.videoData.captionTracks.length)var e=Y.getAudioTrack().L;if(Y.ai.Gi===2){if(g.Uv(Y.ai))var K=lXd(Y);else if(Y.storage)try{K=Y.storage.get("module-enabled")}catch(z){Y.storage.remove("module-enabled")}else K=null;if(K!=null)return!!K}K=RVZ(Y.player.getAudioTrack(),g.Uv(Y.ai));var x=g.w7(Y.videoData,"yt:cc");if(djd(Y)===void 0){if(K==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return x?x==="on":!0;if(K==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return x==="on"}else return x==="on";return e==="ON"||
g.w7(Y.videoData,"yt:cc")==="on"},du=function(Y,e){if(Y.L&&(e===void 0||!e)||!Y.videoData.captionTracks.length)return!1;
Y=Y.getAudioTrack();return!!Y.K||Y.L==="FORCED_ON"},djd=function(Y){var e=void 0,K=g.gC(g.C7(),65);
if(g.Uv(Y.ai)&&K!=null){if(lXd(Y)!=null)return!1;e=!K}return e},ne=function(Y,e){if(!Y.K)return null;
if(Y.C&&Y.C.Y)return Y.C.Y;e=nrn(Y,e);e=g.OA(Y.K.L,e);var K=null;if(mE1(Y.ai)){var x=Y.W.isInline()?void 0:g.MT("yt-player-caption-sticky-language");for(var z=[x,Y.videoData.captionsLanguagePreference,Y.ai.captionsLanguagePreference,g.w7(Y.videoData,"yt:cc_default_lang")],O=!1,T=0;T<z.length;T++){var E=z[T];if(E){O=!0;for(var u=0;u<e.length;u++)if(g.lp(e[u])===E)return e[u];for(u=0;u<e.length;u++)if(g.lp(e[u]).split("-")[0]===E.split("-")[0])return e[u]}}if(O&&Y.K&&(z=Y.K.B,z.length))for(z=g.a(z),
O=z.next();!O.done;O=z.next())if(O=O.value,O.languageCode===x){K=O;break}}else for(x=[Y.videoData.captionsLanguagePreference,Y.ai.captionsLanguagePreference,g.w7(Y.videoData,"yt:cc_default_lang")],z=0;z<x.length;z++)for(O=0;O<e.length;O++)if(g.lp(e[O])===x[z])return e[O];x=null;Y.C&&Y.C.X&&(x=Y.C.X);x||(x=e.find(function(b){return b.isDefault})||null);
x||(x=e[0]||qK(Y));x&&K&&g.lp(x).split("-")[0]!==K.languageCode.split("-")[0]&&(x=XjM(x,K));return x},qK=function(Y){return Y.C&&Y.C.K},wu=function(Y){var e=qK(Y);
return!!e&&Y.L===e},wC0=function(Y,e){var K=Y.W.uq().w2().textTracks;
Y=Y.L.toString();for(var x=0;x<K.length;x++){var z=K[x];z.id===Y&&(e?z.mode!=="showing"&&(z.mode="showing"):z.mode==="showing"&&(z.mode="disabled"))}},Dj=function(Y,e,K){Y.loaded&&Y.unload();
K!=null&&(Y.S=K,Y.S&&(g.Uv(Y.ai)?yv(Y,!!e):IU(Y,!!e)));e!==null||du(Y,!0)||Y.un(e,!!e,Y.S?"m":"s");Y.L=e;du(Y)&&(Y.L=qK(Y));var x;yLq(Y,(x=Y.L)!=null?x:void 0);Y.load()},Djx=function(Y,e){if(e instanceof Pa){var K=Y.LF[e.id];
K&&K.L!==e&&(K.dispose(),delete Y.LF[e.id],K=null);K||(K=IXq(Y,e))&&(Y.LF[e.id]=K)}else K=e.windowId,Y.Sd[K]||(Y.Sd[K]=[]),Y.Sd[K].push(e)},IXq=function(Y,e){var K=tSx(Y);
if(!K)return null;var x=Y.L?g.lp(Y.L):null;x&&g.Mq7.test(x)&&(e.params.cZ=1);var z=Y.CF.getPlayerSize();x=z.height*Y.xq.height;z=z.width*Y.xq.width;Y.ai.playerStyle!=="google-live"||Y.X.isDefault||Object.assign(e.params,Y.X);switch(e.params.sL!=null?e.params.sL:e.K.length>1?1:0){case 1:return new ru(e,Y.X,Y.U,K.width,K.height,z,x,Y.ai.experiments,Y.S2.bind(Y),Y.W);case 2:return new Wa(e,Y.X,Y.U,K.width,K.height,z,x,Y.ai.experiments,Y.S2.bind(Y),Y.W);default:return new Gq(e,Y.X,Y.U,K.width,K.height,
z,x,Y.ai.experiments,Y.S2.bind(Y),Y.W)}},Wtd=function(Y,e,K){K=K===void 0?!1:K;
var x=t2.eI;Y.X={};Object.assign(Y.X,t2);Y.X.eI={};Object.assign(Y.X.eI,x);Y.U={eI:{}};var z=e.backgroundOverride?Y.U:Y.X,O=e.background||x.background;Vv.test(O);z.eI.background=O;z=e.colorOverride?Y.U:Y.X;O=e.color||x.color;Vv.test(O);z.eI.color=O;z=e.windowColorOverride?Y.U:Y.X;O=e.windowColor||t2.windowColor;Vv.test(O);z.windowColor=O;z=e.backgroundOpacityOverride?Y.U:Y.X;O=e.backgroundOpacity;O==null&&(O=x.backgroundOpacity);z.eI.backgroundOpacity=O;z=e.fontSizeIncrementOverride?Y.U:Y.X;O=e.fontSizeIncrement;
O==null&&(O=x.fontSizeIncrement);z.eI.fontSizeIncrement=O;O=e.fontStyleOverride?Y.U:Y.X;z=e.fontStyle;z==null&&(z=x.bold&&x.italic?3:x.bold?1:x.italic?2:0);O=O.eI;switch(z){case 1:O.bold=!0;delete O.italic;break;case 2:delete O.bold;O.italic=!0;break;case 3:O.bold=!0;O.italic=!0;break;default:delete O.bold,delete O.italic}z=e.textOpacityOverride?Y.U:Y.X;O=e.textOpacity;O==null&&(O=x.textOpacity);z.eI.textOpacity=O;z=e.windowOpacityOverride?Y.U:Y.X;O=e.windowOpacity;O==null&&(O=t2.windowOpacity);z.windowOpacity=
O;z=e.charEdgeStyleOverride?Y.U:Y.X;O=e.charEdgeStyle;O==null&&(O=x.charEdgeStyle);z.eI.charEdgeStyle=O;z=e.fontFamilyOverride?Y.U:Y.X;O=e.fontFamily;O==null&&(O=x.fontFamily);z.eI.fontFamily=O;Y.loaded&&Y.Tn();K&&g.Pp("yt-player-caption-display-settings",e,2592E3)},Ycq=function(Y,e){if(!Y.K)return{};
if(e){g.kM(e)||Y.z7(e.vss_id,"m");if(Y.B||!g.$x(e))return;if(g.kM(e)){Dj(Y,null,!0);return}for(var K,x=g.OA(Y.K.L,!0),z=0;z<x.length;z++){var O=x[z];O.languageCode!==e.languageCode||K&&(O.languageName!==e.languageName||(O.captionId||"")!==(e.captionId||"")||g.Wm(O)!==e.displayName)||(K=e.translationLanguage?XjM(O,e.translationLanguage):O)}Y.qZ(e.position);!K||K===Y.L&&Y.loaded||(e=g.mK(),x=g.lp(K),e.length&&x===e[e.length-1]||(e.push(x),g.Pp("yt-player-caption-language-preferences",e)),mE1(Y.ai)&&
!Y.W.isInline()&&g.Pp("yt-player-caption-sticky-language",x,2592E3),Dj(Y,K,!0))}else return Y.loaded&&Y.L&&!wu(Y)?g.Hm(Y.L):{};return""},KM1=function(Y,e,K){e&&!Y.nF?(e=ord({cZ:0,
lang:"ko"}),Y.nF=[e,new Qv(e.start,e.end-e.start,0,e.id,K!=null?K:"\uc790\ub9c9\uc740 \uc774\ub807\uac8c \ud45c\uc2dc\ub429\ub2c8\ub2e4.")],Y.player.B_(Y.nF)):!e&&Y.nF&&(en0(Y,Y.nF),Y.nF=null)},en0=function(Y,e){Y.player.c$(e);
e=g.a(e);for(var K=e.next();!K.done;K=e.next())g.QU(Y.fF,K.value);bP(Y.Yq)},yLq=function(Y,e){Y.ai.Z("html5_modify_caption_vss_logging")&&(Y.videoData.JH=e)},tSx=function(Y){var e=Y.CF.getVideoContentRect(!0).height,K=Y.CF.getVideoContentRect(!0).width;
if(!e||!K)return null;e*=Y.xq.height;K*=Y.xq.width;return{width:K,height:e}},IU=function(Y,e){if(Y.storage)try{Y.storage.set("module-enabled",e)}catch(K){}},yv=function(Y,e){Y.W.isInline()||g.Pp("yt-player-sticky-caption",e,2592E3)},lXd=function(Y){if(!Y.W.isInline())return g.MT("yt-player-sticky-caption")},Ssz=function(Y){var e,K=!((e=Y.W.uq())==null||!e.AP());
return Y.Vq&&K&&Y.Y!=="LIVE"&&Y.Y!=="SABR_LIVE"},nrn=function(Y,e){g.Tv(Y.videoData)&&(e=!0);
e||(e=Y.Y==="TTS"?!1:Y.Y==="INNERTUBE"?!1:!0);return e||Y.ai.Z("web_deprecate_always_includes_asr_setting")&&g.Uv(Y.ai)?!0:!!g.gC(g.C7(),66)};
g.Z5.prototype.zN=g.sp(71,function(){return!1});
g.Z5.prototype.jA=g.sp(70,function(){});
g.ps.prototype.jA=g.sp(69,function(Y,e,K){var x=this;this.qT();e=this.N2(Y,e);var z=this.s4.D().Z("html5_report_captions_ctmp_qoe"),O=(0,g.mJ)();this.Il();f6A(this,e,{format:"RAW",onSuccess:function(T){x.K=null;if(z){var E=(T.responseText.length/1024).toFixed(),u=(0,g.mJ)();x.videoData.Ii("capresp",{ms:u-O,kb:E})}K.pk(T.responseText,Y)},
onError:z?function(T){var E;T=(E=T==null?void 0:T.status)!=null?E:0;x.videoData.Ii("capfail",{status:T})}:void 0,
withCredentials:!0})});
g.Vm.prototype.jA=g.sp(68,function(Y,e,K){var x=this;this.qT();e=this.N2(Y,e);this.Il();this.K=g.RE(e,{format:"RAW",onSuccess:function(z){x.K=null;K.pk(z.responseText,Y)},
withCredentials:!0})});
g.Iz.prototype.e6=g.sp(67,function(){for(var Y=g.Oj(document,"track",void 0,this.K),e=0;e<Y.length;e++)g.Rb(Y[e])});
g.Ww.prototype.e6=g.sp(66,function(){this.mediaElement.e6()});
g.Iz.prototype.Xn=g.sp(65,function(){return!(!this.K.textTracks||!this.K.textTracks.addEventListener)});
g.Ww.prototype.Xn=g.sp(64,function(){return this.mediaElement.Xn()});
g.Iz.prototype.AP=g.sp(63,function(){return!!this.K.textTracks});
g.Ww.prototype.AP=g.sp(62,function(){return this.mediaElement.AP()});
g.Iz.prototype.wA=g.sp(61,function(Y){for(var e=0;e<Y.length;e++)this.K.appendChild(Y[e])});
g.Ww.prototype.wA=g.sp(60,function(Y){this.mediaElement.wA(Y)});
g.bK.prototype.Fj=g.sp(59,function(Y,e,K){this.Wn.Fj(Y,e,K)});
g.Kn.prototype.Fj=g.sp(58,function(Y,e,K){this.L.set(Y,{h1:e,O2:K})});
g.xA.prototype.Fj=g.sp(57,function(Y,e,K){this.xq.Fj(Y,e,K)});
g.bK.prototype.Lg=g.sp(56,function(Y){return this.Wn.Lg(Y)});
g.xA.prototype.Lg=g.sp(55,function(Y){var e=2;this.B.has(Y)?e=0:g.TY8(this,Y)&&(e=1);return e});
g.d0.prototype.Jj=g.sp(43,function(Y){var e=this.app.ge({playerType:void 0});return e?e.Jj(Y):!1});
g.$w.prototype.Jj=g.sp(42,function(Y){return this.kq.pj.Jj(Y)});
g.vo.prototype.Jj=g.sp(41,function(Y){return this.rU().some(function(e){return e.namespace===Y})});
g.n_.prototype.Jj=g.sp(40,function(){return!1});
g.d0.prototype.z7=g.sp(38,function(Y,e){this.app.Jo().z7(Y,e)});
g.$w.prototype.z7=g.sp(37,function(Y,e){this.kq.z7(Y,e)});
g.sb.prototype.z7=g.sp(36,function(Y,e){Y=[Y,e];g.x2(this,g.$2(this.provider),"cfi",Y)});
g.AX.prototype.z7=g.sp(35,function(Y,e){this.qoe&&this.qoe.z7(Y,e)});
g.OC.prototype.z7=g.sp(34,function(Y,e){this.US.z7(Y,e)});
g.n_.prototype.z7=g.sp(33,function(){});
g.d0.prototype.un=g.sp(32,function(Y,e,K){this.app.Jo().un(Y,e,K)});
g.$w.prototype.un=g.sp(31,function(Y,e,K){this.kq.un(Y,e,K)});
g.sb.prototype.un=g.sp(30,function(Y,e,K){if(this.Yq!==Y||this.jL!==e)e=e==="rawcc"?"":e,K=[Y,e,this.Yq,K],g.x2(this,g.$2(this.provider),"cfs",K),this.Yq=Y,this.jL=e});
g.AX.prototype.un=g.sp(29,function(Y,e,K){this.qoe&&this.qoe.un(Y,e,K)});
g.OC.prototype.un=g.sp(28,function(Y,e,K){this.US.un(Y,e,K)});
g.n_.prototype.un=g.sp(27,function(){});
g.uK.prototype.l3=g.sp(12,function(){return this.S});
g.fn.prototype.l3=g.sp(11,function(){return this.Jo().Ud()});
g.d0.prototype.Ud=g.sp(10,function(){return this.app.l3()});
g.$w.prototype.Ud=g.sp(9,function(){return this.kq.Ud()});
g.OC.prototype.Ud=g.sp(8,function(){var Y;return((Y=this.loader)==null?void 0:Y.l3())||null});
g.n_.prototype.Ud=g.sp(7,function(){return null});
g.eh.prototype.nZ=g.sp(1,function(Y){return(Y=this.Y$(Y))?Y.K:0});
g.p2.prototype.nZ=g.sp(0,function(){return 0});
var hVn=/#(.)(.)(.)/,QHA=/^#(?:[0-9a-f]{3}){1,2}$/i,CFz={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kk_Cyrl:"Kazakh (Cyrillic)",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kok_Deva:"Konkani (Devanagari)",kok_Latn:"Konkani (Latin)",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",
kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",
man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",
my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",
nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",
raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",
sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",
ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",
tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",
wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",
zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};kJ.prototype.contains=function(Y){Y=g.Wz(this.segments,Y);return Y>=0||Y<0&&(-Y-1)%2===1};
kJ.prototype.length=function(){return this.segments.length/2};
g.m(pjz,g.J);g.R=pjz.prototype;g.R.KF=function(){g.J.prototype.KF.call(this);this.X&&this.X.cancel()};
g.R.UT=function(){this.seekTo(this.player.getCurrentTime())};
g.R.seekTo=function(Y){Y-=this.player.ES();var e=this.K;this.K=g.La(this.nF.oh(Y).zZ);e!==this.K&&this.C&&this.C()};
g.R.reset=function(){this.Y=new kJ;this.U=-1;this.X&&(this.X.cancel(),this.X=null)};
g.R.aj=function(){this.qT();var Y;if(Y=this.K!=null)Y=this.K,Y=Y.K.TD(Y);if(Y&&!this.X&&!(this.K&&this.K.startTime-this.player.getCurrentTime()>30)){Y=this.K;Y=Y.K.l5(Y);var e=Y.zZ[0],K;if((K=this.player.getVideoData())==null?0:K.enableServerStitchedDai)if(K=this.player.Ud()){var x=e.K.info.id,z=e.d7,O=Y.zZ[0].B;if(this.policy.fF){if(K=K.Qz(O,z,x,3))Y.Y=K}else if(x=K.lT(O,z,x,3))if(K=K.Lg(z),K===0)x&&(Y.K=new g.qH(x));else if(K===2){this.T.start();cgA(this)&&this.seekTo(this.player.getCurrentTime());
return}}e.K.index.B9(e.d7)?(this.Y.contains(Y.zZ[0].d7)||VWM(this,Y),this.K=g.La(Y.zZ)):cgA(this)&&this.seekTo(this.player.getCurrentTime())}this.T.start()};
g.m(oU,g.Z5);g.R=oU.prototype;g.R.jA=function(Y,e,K){var x=this;this.Il();e=Agn(this,Y.getId());e||(e=Y.languageCode,e=this.K.isManifestless?vsU(this,e,"386"):vsU(this,e));if(e){var z=(e.index.nZ(e.index.t2())-e.index.getStartTime(e.index.t2()))*1E3,O=this.W.D(),T=new g.W$$(O),E=function(){x.Y&&x.Y.reset();x.U=!0};
O.Z("html5_keep_caption_data_after_seek")&&(E=null);this.Y=new pjz(T,this.W,e,function(u,b){K.pk(u,Y,b,z)},this.T||g.wk(e.info),E)}};
g.R.zN=function(){var Y=this.U;this.U=!1;return Y};
g.R.nB=function(Y){var e=this.W.D().Z("html5_fallback_if_rawcc_missing");var K=this.K.K.rawcc!=null;if(!this.T||!K&&e)e=this.K.isManifestless?gsZ(this,"386"):gsZ(this);else{if(!K){this.logger.K(386248249,"rawcc used but unavailable");return}e=[new g.SC({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.SC({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}e=g.a(e);
for(K=e.next();!K.done;K=e.next())g.Ns(this.L,K.value);Y.j1()};
g.R.Il=function(){this.Y&&(this.Y.dispose(),this.Y=null)};
g.R.N2=function(){return""};
var Vv=/^#(?:[0-9a-f]{3}){1,2}$/i;var iJn=["left","right","center","justify"];g.m(Gq,g.d);g.R=Gq.prototype;g.R.qm=function(Y,e){this.Vq=Y;this.TZ=e;var K=g.Y1(this.element,this.element.parentElement);this.uJ=Y-K.x;this.CF=e-K.y};
g.R.Nm=function(Y,e){if(Y!==this.Vq||e!==this.TZ){g.tA(this.element,"ytp-dragging")||g.YI(this.element,"ytp-dragging");var K=g.Kh(this.element);Y=Y-this.uJ-.02*this.vn;var x=e-this.CF-.02*this.ao,z=(Y+K.width/2)/this.maxWidth*3;z=Math.floor(g.JQ(z,0,2));var O=(x+K.height/2)/this.maxHeight*3;O=Math.floor(g.JQ(O,0,2));e=z+O*3;Y=(Y+z/2*K.width)/this.maxWidth;Y=g.JQ(Y,0,1)*100;K=(x+O/2*K.height)/this.maxHeight;K=g.JQ(K,0,1)*100;this.L.params.eU=e;this.L.params.xH=K;this.L.params.N9=Y;this.L.params.isDefault=
!1;this.K.eU=e;this.K.xH=K;this.K.N9=Y;this.K.isDefault=!1;this.xq.eU=e;this.xq.xH=K;this.xq.N9=Y;this.xq.isDefault=!1;this.qC()}};
g.R.dZ=function(){g.Kw(this.element,"ytp-dragging")};
g.R.qC=function(){this.N3(this.T)};
g.R.N3=function(Y){var e=this.bJ?0:Math.min(this.pu(),this.maxWidth),K=this.X7(),x=this.bJ;if(x){var z=getComputedStyle(this.Y.parentNode);z=Ba(z.borderLeftWidth)+Ba(z.borderRightWidth)+Ba(z.paddingLeft)+Ba(z.paddingRight)}else z=0;var O=z;z="";this.L.params.cZ===3&&(z="rotate(180deg)");var T=x?"calc(96% - "+O+"px)":"96%";g.ln(this.element,{top:0,left:0,right:"",bottom:"",width:e?e+"px":"",height:K?K+"px":"","max-width":T,"max-height":T,margin:"",transform:""});this.Th(Y);z={transform:z,top:"",left:"",
width:e?e+"px":"",height:K?K+"px":"","max-width":"","max-height":""};var E=this.K.N9*.96+2;T=this.K.eU;switch(T){case 0:case 3:case 6:(x=this.K.eI.fontSizeIncrement)&&x>0&&this.K.cZ!==2&&this.K.cZ!==3&&(E=Math.max(E/(1+x*2),2));z.left=E+"%";break;case 1:case 4:case 7:z.left=E+"%";E=this.Y.offsetWidth;e||E?(e=e||E+1,z.width=e+"px",z["margin-left"]=x?e/-2-O/2+"px":e/-2+"px"):z.transform+=" translateX(-50%)";break;case 2:case 5:case 8:z.right=100-E+"%"}x=this.K.xH*.96+2;switch(T){case 0:case 1:case 2:z.top=
x+"%";break;case 3:case 4:case 5:z.top=x+"%";(K=K||this.element.clientHeight)?(z.height=K+"px",z["margin-top"]=K/-2+"px"):z.transform+=" translateY(-50%)";break;case 6:case 7:case 8:z.bottom=100-x+"%"}g.ln(this.element,z);if(this.U){K=this.Y.offsetHeight;x=1;for(e=0;e<Y.length;e++)z=Y[e],typeof z.text==="string"&&(x+=z.text.split("\n").length-1,z.append||e===0||x++);K/=x;this.U.style.height=K+"px";this.U.style.width=K+"px";this.element.style.paddingLeft=K+5+"px";this.element.style.paddingRight=K+
5+"px";Y=Number(this.element.style.marginLeft.replace("px",""))-K-5;K=Number(this.element.style.marginRight.replace("px",""))-K-5;this.element.style.marginLeft=Y+"px";this.element.style.marginRight=K+"px"}};
g.R.Th=function(Y){var e;for(e=0;e<Y.length&&Y[e]===this.T[e];e++);if(this.X6||this.T.length>e)e=0,this.X6=!1,this.T=[],this.S=this.Yq=this.fF=null,g.Ly(this.Y);for(;e<Y.length;e++)l6n(this,Y[e])};
g.R.pu=function(){return 0};
g.R.X7=function(){return 0};
g.R.toString=function(){return g.d.prototype.toString.call(this)};qW6.prototype.clear=function(){this.X=this.time=this.mode=0;this.K=[];this.reset()};
qW6.prototype.reset=function(){this.mode=0;this.Y.reset(0);this.B.reset(1)};
var nsP=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];Le.prototype.set=function(Y){this.type=Y};
Le.prototype.get=function(){return this.type};
fe.prototype.clear=function(){this.state=0};
fe.prototype.update=function(){this.state=this.state===2?1:0};
fe.prototype.c_=function(){return this.state!==0};
fe.prototype.matches=function(Y,e){return this.c_()&&Y===this.Dj&&e===this.Ob};
tW1.prototype.reset=function(){this.timestamp=this.K=0};
RU.prototype.updateTime=function(Y){for(var e=1;e<=15;++e)for(var K=1;K<=32;++K)this.X[e][K].timestamp=Y};
RU.prototype.debugString=function(){for(var Y="\n",e=1;e<=15;++e){for(var K=1;K<=32;++K){var x=this.X[e][K];Y=x.K===0?Y+"_":Y+String.fromCharCode(x.K)}Y+="\n"}return Y};
RU.prototype.reset=function(Y){for(var e=0;e<=15;e++)for(var K=0;K<=32;K++)this.X[e][K].reset();this.Y=Y;this.K=0;this.L=this.row=1};
var Ys7=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],eTA=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],KtM=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],xjU=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];OOa.prototype.reset=function(Y,e){this.B=e;this.style.set(2);this.L=this.U;this.Y=this.T;this.K=this.L;var K=(Y<<2)+(e<<1);this.U.reset(K);this.T.reset(K);this.text.reset((Y<<2)+(e<<1)+1)};
dEx.prototype.reset=function(Y){this.B=Y;this.L.clear();this.Y=this.X;this.X.reset(Y,0);this.U.reset(Y,1)};u$d.prototype.Y=function(){};g.m(Qv,g.HU);Qv.prototype.toString=function(){return g.HU.prototype.toString.call(this)};g.m(h2,g.J);h2.prototype.reset=function(){};g.m(Pa,g.HU);Pa.prototype.toString=function(){return g.HU.prototype.toString.call(this)};
var MK=0;g.m(NK,h2);NK.prototype.reset=function(){this.T={};this.L=this.K=null;this.U=!0};
NK.prototype.X=function(Y,e){Y=Y.firstChild;Y.getAttribute("format");e=e||0;Number.isFinite(e);Y=Array.from(Y.childNodes);Y=g.a(Y);for(var K=Y.next();!K.done;K=Y.next())if(K=K.value,K.nodeType===1)switch(K.tagName){case "head":var x=K;break;case "body":var z=K}if(x)for(x=Array.from(x.childNodes),x=g.a(x),Y=x.next();!Y.done;Y=x.next())if(Y=Y.value,Y.nodeType===1)switch(Y.tagName){case "pen":K=Y.getAttribute("id");var O=this.pens,T={},E=Y.getAttribute("p");E&&Object.assign(T,this.pens[E]);E=pe(Y,"b");
E!=null&&(T.bold=E);E=pe(Y,"i");E!=null&&(T.italic=E);E=pe(Y,"u");E!=null&&(T.underline=E);E=ca(Y,"et");E!=null&&(T.charEdgeStyle=E);E=ca(Y,"of");E!=null&&(T.offset=E);E=Ce(Y,"bc");E!=null&&(T.background=E);E=Ce(Y,"ec");E!=null&&(T.Qv=E);E=Ce(Y,"fc");E!=null&&(T.color=E);E=ca(Y,"fs");E!=null&&E!==0&&(T.fontFamily=E);E=Zj(Y,"sz");E!==void 0&&(T.fontSizeIncrement=E/100-1);E=Zj(Y,"bo");E!==void 0&&(T.backgroundOpacity=E/255);E=Zj(Y,"fo");E!==void 0&&(T.textOpacity=E/255);E=ca(Y,"rb");E!=null&&E!==10&&
E!==0&&(T.hv=E>10?E-1:E);Y=ca(Y,"hg");Y!=null&&(T.AE=Y);O[K]=T;break;case "ws":K=Y.getAttribute("id");this.C[K]=G$U(this,Y);break;case "wp":K=Y.getAttribute("id"),this.S[K]=Bid(this,Y)}if(z){x=[];z=Array.from(z.childNodes);z=g.a(z);for(Y=z.next();!Y.done;Y=z.next())if(Y=Y.value,Y.nodeType===1)switch(Y.tagName){case "w":this.K=Lt1(this,Y,e,!1);(Y=this.T[this.K.id])&&Y.end>this.K.start&&(Y.end=this.K.start);this.T[this.K.id]=this.K;x.push(this.K);break;case "p":var u=Y;E=e;K=[];O=u.getAttribute("w")||
this.B;T=!!pe(u,"a");E=(Zj(u,"t")||0)+E;var b=Zj(u,"d")||5E3;T||(!this.U&&this.L&&this.L.windowId===O&&this.L.end>E&&(this.L.end=E),this.L&&this.L.text==="\n"&&(this.L.text=""));var k=T?6:5,G=u.getAttribute("p");G=G?this.pens[G]:null;var B=Array.from(u.childNodes);B.length&&(this.U=u.getAttribute("d")!=null);for(u=0;u<B.length;u++){var L=B[u],f=void 0;u>0&&(T=!0);var U=void 0;L.nodeType===1&&(U=L);if(U&&U.tagName==="s"){if((L=(L=U.getAttribute("p"))?this.pens[L]:null)&&L.hv&&(L.hv===1?(L=B.slice(u,
u+4),L.length===4&&(f=k$P(E,b,O,T,k,L,this.pens),u+=3)):f=k$P(E,b,O,T,k,[U],this.pens)),!f){var h=U;f=E;U=b;L=O;var Z=T,N=k,V=h.textContent?h.textContent:"",r=h.getAttribute("p");r=r?this.pens[r]:null;h=Zj(h,"t")||0;f=new Qv(f+h,U-h,N,L,V,Z,r)}}else f=new Qv(E,b,k,O,L.textContent||"",T,G);K.push(f);this.L=f}if(K.length>0)for(K[0].windowId===this.B&&(this.K=Lt1(this,Y,e,!0),x.push(this.K)),Y=g.a(K),K=Y.next();!K.done;K=Y.next())K=K.value,K.windowId=this.K.id,this.K.K.push(K),x.push(K)}e=x}else e=[];
return e};var x4U=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.m(gu,h2);gu.prototype.reset=function(){this.L.clear()};
gu.prototype.X=function(Y,e){var K=JSON.parse(Y);if(!K)return[];if(K.pens){Y=0;for(var x=g.a(K.pens),z=x.next();!z.done;z=x.next()){z=z.value;var O={},T=z.pParentId;T&&Object.assign(O,this.K.get(T));z.bAttr&&(O.bold=!0);z.iAttr&&(O.italic=!0);z.uAttr&&(O.underline=!0);T=z.ofOffset;T!=null&&(O.offset=T);z.szPenSize!==void 0&&(O.fontSizeIncrement=z.szPenSize/100-1);T=z.etEdgeType;T!=null&&(O.charEdgeStyle=T);z.ecEdgeColor!==void 0&&(O.Qv=A2(z.ecEdgeColor));T=z.fsFontStyle;T!=null&&T!==0&&(O.fontFamily=
T);z.fcForeColor!==void 0&&(O.color=A2(z.fcForeColor));z.foForeAlpha!==void 0&&(O.textOpacity=z.foForeAlpha/255);z.bcBackColor!==void 0&&(O.background=A2(z.bcBackColor));z.boBackAlpha!==void 0&&(O.backgroundOpacity=z.boBackAlpha/255);(T=z.rbRuby)&&T!==10&&(O.hv=T>10?T-1:T,O.textEmphasis=x4U.get(O.hv));z.hgHorizGroup&&(O.AE=z.hgHorizGroup);this.K.set(Y++,O)}}if(K.wsWinStyles)for(Y=0,x=g.a(K.wsWinStyles),z=x.next();!z.done;z=x.next())z=z.value,O={},(T=z.wsParentId)?Object.assign(O,this.B.get(T)):Object.assign(O,
this.U),z.mhModeHint!==void 0&&(O.sL=z.mhModeHint),z.juJustifCode!==void 0&&(O.textAlign=z.juJustifCode),z.pdPrintDir!==void 0&&(O.cZ=z.pdPrintDir),z.sdScrollDir!==void 0&&(O.R7=z.sdScrollDir),z.wfcWinFillColor!==void 0&&(O.windowColor=A2(z.wfcWinFillColor)),z.wfoWinFillAlpha!==void 0&&(O.windowOpacity=z.wfoWinFillAlpha/255),this.B.set(Y++,O);if(K.wpWinPositions)for(Y=0,x=g.a(K.wpWinPositions),z=x.next();!z.done;z=x.next())z=z.value,O={},(T=z.wpParentId)&&Object.assign(O,this.Y.get(T)),z.ahHorPos!==
void 0&&(O.N9=z.ahHorPos),z.apPoint!==void 0&&(O.eU=z.apPoint),z.avVerPos!==void 0&&(O.xH=z.avVerPos),z.ccCols!==void 0&&(O.im=z.ccCols),z.rcRows!==void 0&&(O.hx=z.rcRows),this.Y.set(Y++,O);if(K.events){Y=[];K=g.a(K.events);for(x=K.next();!x.done;x=K.next()){var E=x.value;z=(E.tStartMs||0)+e;O=E.dDurationMs||0;if(E.id)T=String(E.id),x=fXx(this,E,z,O,T),Y.push(x),this.L.set(T,x);else{E.wWinId?T=E.wWinId.toString():(T="_"+MK++,x=fXx(this,E,z,O,T),Y.push(x),this.L.set(T,x));x=Y;var u=E;O===0&&(O=5E3);
E=this.L.get(T);var b=!!u.aAppend,k=b?6:5,G=u.segs,B=null;u.pPenId&&(B=this.K.get(u.pPenId));for(u=0;u<G.length;u++){var L=G[u],f=L.utf8;if(f){var U=L.tOffsetMs||0,h=null;L.pPenId&&(h=this.K.get(L.pPenId));if((E.params.sL!=null?E.params.sL:E.K.length>1?1:0)===2&&b&&f==="\n")continue;L=null;var Z=[],N;if(N=h&&h.hv===1){N=G;var V=u;if(V+3>=N.length||!N[V+1].pPenId||!N[V+2].pPenId||!N[V+3].pPenId)N=!1;else{var r=N[V+1].pPenId;(r=this.K.get(r))&&r.hv&&r.hv===2?(r=N[V+2].pPenId,r=this.K.get(r),!r||!r.hv||
r.hv<3?N=!1:(r=N[V+3].pPenId,N=(r=this.K.get(r))&&r.hv&&r.hv===2?!0:!1)):N=!1}}if(N)U=G[u+1].utf8,L=G[u+3].utf8,N=G[u+2].utf8,V=this.K.get(G[u+2].pPenId),f=bOn(f,U,N,L,V),L=new Qv(z,O,k,T,f,b,h),u+=3;else{if(f.indexOf("<")>-1){var H=void 0;Z=h;N=B;V=z;r=O;var I=U,w=k,$O=b,GM=[],TM=g.IQ("<html>"+f+"</html>");if(!TM.getElementsByTagName("parsererror").length&&((H=TM.firstChild)==null?0:H.childNodes.length))for(H=g.a(TM.firstChild.childNodes),TM=H.next();!TM.done;TM=H.next()){TM=TM.value;var F9=void 0,
ec=void 0,NP=(ec=(F9=TM.textContent)==null?void 0:F9.replace(/\n/g,""))!=null?ec:"";if(TM.nodeType!==3||NP&&NP.match(/^ *$/)==null){F9={};Object.assign(F9,Z||N);ec=void 0;switch((ec=TM)==null?void 0:ec.tagName){case "b":F9.bold=!0;break;case "i":F9.italic=!0;break;case "u":F9.underline=!0}GM.push(new Qv(V+I,r-I,w,E.id,NP,$O,F9))}}Z=GM}Z.length||(Z=[new Qv(z+U,O-U,k,E.id,f,b,h||B)])}if(Z.length)for(b=g.a(Z),h=b.next();!h.done;h=b.next())h=h.value,x.push(h),E.K.push(h);else L&&(x.push(L),E.K.push(L))}b=
!0}}}e=Y}else e=[];return e};g.m(va,g.Z5);va.prototype.jA=function(Y,e,K){UE1(this.videoData.videoId,Y.vssId,K.pk)};
va.prototype.nB=function(Y){if(this.audioTrack)for(var e=g.a(this.audioTrack.captionTracks),K=e.next();!K.done;K=e.next())g.Ns(this.L,K.value);Y.j1()};g.m(ru,Gq);ru.prototype.Th=function(Y){var e=this.L.K;Gq.prototype.Th.call(this,Y);for(Y=Y.length;Y<e.length;Y++){var K=e[Y];if(O&&K.K===z)var x=O;else{x={};Object.assign(x,K.K);Object.assign(x,zna);var z=K.K;var O=x}l6n(this,K,x)}};
var zna={Q6:!0};g.m(jQ,u$d);jQ.prototype.Y=function(Y,e,K,x,z){if(K<x){var O="_"+MK++;K=K/1E3-this.U;x=x/1E3-this.U;Y=new Pa(K,x-K,5,O,{textAlign:0,eU:0,N9:e*2.5,xH:Y*5.33});z=new Qv(K,x-K,5,O,z);this.L.push(Y);this.L.push(z)}};
g.m(SQ,h2);SQ.prototype.X=function(Y){Y=new jQ(Y,Y.byteLength,this.L);if(RTA(Y)){for(;Y.byteOffset<Y.K.byteLength;)for(Y.version===0?Y.X=J2(Y)*(1E3/45):Y.version===1&&(Y.X=J2(Y)*4294967296+J2(Y)),Y.B=iP(Y);Y.B>0;Y.B--){var e=iP(Y),K=iP(Y),x=iP(Y);e&4&&(e&3)===this.track&&(this.track===0||this.track===1)&&(e=this.K,e.K.push({time:Y.X,type:this.track,bF:K,aB:x,order:e.K.length}))}DEM(this.K,Y);return Y.L}return[]};
SQ.prototype.reset=function(){this.K.clear()};g.m(Wa,Gq);g.R=Wa.prototype;g.R.qC=function(){g.d6(this.Iq)};
g.R.ow=function(){this.element.removeEventListener("transitionend",this.ow,!1);g.Kw(this.element,"ytp-rollup-mode");this.N3(this.sS,!0)};
g.R.X7=function(){return this.X?this.nF:this.C};
g.R.pu=function(){return this.X?this.C:this.nF};
g.R.N3=function(Y,e){this.sS=Y;if(this.L.params.hx){for(var K=0,x=0;x<this.T.length&&K<Y.length;x++)this.T[x]===Y[K]&&K++;K>0&&K<Y.length&&(Y=this.T.concat(Y.slice(K)));this.x3=this.nF;this.C=this.nF=0;Gq.prototype.N3.call(this,Y);Uj1(this,e)}Gq.prototype.N3.call(this,Y)};Qfq.prototype.unload=function(){this.K!=null&&(this.W.removeEventListener("sabrCaptionsDataLoaded",this.K),this.K=null);this.kJ=[];this.W.publish("sabrCaptionsBufferedRangesUpdated",this.kJ)};
Qfq.prototype.vH=function(Y){return{formatId:g.DR(Y.info.K.info,this.qn),d7:Y.info.d7+(this.qn?0:1),startTimeMs:Y.info.B*1E3,durationMs:Y.info.S*1E3}};g.m(Ha,g.Z5);Ha.prototype.jA=function(Y,e,K){this.Il();e=Y.getId();e=e!=null&&e in this.K.K?this.K.K[e]:null;e||(e=Y.languageCode,e=this.K.isManifestless?ZOq(this,e,"386"):ZOq(this,e));e&&(this.Y=Y,this.U=e,MS7(this.T,K),this.W.publish("sabrCaptionsTrackChanged",g.DR(e.info,this.K.qn)))};
Ha.prototype.nB=function(Y){var e=this.K.isManifestless?NiZ(this,"386"):NiZ(this);e=g.a(e);for(var K=e.next();!K.done;K=e.next())g.Ns(this.L,K.value);Y.j1()};
Ha.prototype.Il=function(){this.Y&&(this.Y=this.U=null,this.T.unload(),this.W.publish("sabrCaptionsTrackChanged",null))};
Ha.prototype.N2=function(){return""};var VSA="WEBVTT".split("").map(function(Y){return Y.charCodeAt(0)});
g.m(cLL,h2);
cLL.prototype.X=function(Y,e){Y instanceof ArrayBuffer&&(Y=g.km(new Uint8Array(Y)));var K=[];Y=Y.split($4L);for(var x=1;x<Y.length;x++){var z=Y[x],O=e;if(z!==""&&!OZU.test(z)){var T=TL1.exec(z);if(T&&T.length>=4){var E=ALn(T[1]),u=ALn(T[2])-E;E+=O;var b=(T=T[3])?T.split(" "):[];T={};var k=null;var G="";var B=null,L="";b=g.a(b);for(var f=b.next();!f.done;f=b.next())if(f=f.value.split(":"),f.length===2){var U=f[1];switch(f[0]){case "line":f=U.split(",");f[0].endsWith("%")&&(k=f[0],T.xH=Number.parseInt(k,
10),f.length===2&&(G=f[1].trim()));break;case "position":f=U.split(",");B=f[0];T.N9=Number.parseInt(B,10);f.length===2&&(L=f[1].trim());break;case "align":switch(U){case "start":T.textAlign=0;break;case "middle":T.textAlign=2;break;case "end":T.textAlign=1}}}k||G||(G="end");if(!B)switch(T.textAlign){case 0:T.N9=0;break;case 1:T.N9=100;break;case 2:T.N9=50}if(T.textAlign!=null){k=0;switch(G){case "center":k+=3;break;case "end":k+=6;break;default:k+=0}switch(L){case "line-left":k+=0;break;case "center":k+=
1;break;case "line-right":k+=2;break;default:switch(T.textAlign){case 0:k+=0;break;case 2:k+=1;break;case 1:k+=2}}G=k<0||k>8?7:k;T.eU=G}z=z.substring(TL1.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");L=T;T=z;z={};if(T.indexOf("<")<0&&T.indexOf("&")<0)O=vrZ(E,u,5,L),u=new Qv(E,u,5,O.id,T,!1,g.kM(z)?void 0:z),K.push(O),K.push(u),O.K.push(u);else for(G=T.split(FM1),G.length===1?(T=5,L=vrZ(E,u,T,L)):(k=T=6,L=Object.assign({im:32},L),L=new Pa(E,u,k,"_"+MK++,L)),K.push(L),k=E,B=0;B<G.length;B++)b=G[B],
B%2===0?(f=g.IQ("<html>"+b+"</html>"),f.getElementsByTagName("parsererror").length?(U=f.createElement("span"),U.appendChild(f.createTextNode(b))):U=f.firstChild,grn(this,k,u-(k-E),T,L,B>0,U,z,K)):k=ALn(b)+O}TL1.lastIndex=0}}return K};
var OZU=/^NOTE/,$4L=/(?:\r\n|\r|\n){2,}/,TL1=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),FM1=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.m(lP,g.J);lP.prototype.clear=function(){this.K&&this.K.dispose();this.K=null};
lP.prototype.reset=function(){this.K&&this.K.reset()};
lP.prototype.KF=function(){g.J.prototype.KF.call(this);this.clear()};var t2={windowColor:"#080808",windowOpacity:0,textAlign:2,eU:7,N9:50,xH:100,isDefault:!0,eI:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.m(HOd,g.Ms);g.R=HOd.prototype;g.R.KF=function(){if(this.B||this.pF){var Y=this.W.uq();Y&&!Y.qT()&&Y.e6()}else KM1(this,!1);g.Ms.prototype.KF.call(this)};
g.R.ih=function(){return this.ai.Z("html5_honor_caption_availabilities_in_audio_track")&&this.Y!=="LIVE"&&this.Y!=="SABR_LIVE"};
g.R.JT=function(){if(this.Vq)return this.B||this.pF;var Y=this.getAudioTrack();if(this.ih()){if(!Y.captionTracks.length)return!1;if(!this.K)return!0}Y=RVZ(Y,g.Uv(this.ai));return Y==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:Y==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?du(this):djd(this)||du(this)?!0:qs6(this)};
g.R.load=function(){g.Ms.prototype.load.call(this);this.C=this.getAudioTrack();if(this.K)this.L&&(this.TZ.clear(),this.B?wC0(this,!0):this.player.getPresentingPlayerType()!==3&&this.K.jA(this.L,"json3",this.Iq),this.B||this.pF||wu(this)||this.player.IH("captionschanged",g.Hm(this.L)));else{var Y;this.Y==="OFFLINE"?Y=new va(this.player,this.videoData,this.getAudioTrack()):this.Y==="SABR_LIVE"?Y=new Ha(this.videoData.K,this.player):this.Y==="LIVE"?Y=new oU(this.videoData.K,this.player):this.Y==="INNERTUBE"?
Y=new g.ps(this.player,this.videoData,this.getAudioTrack()):Y=new g.Vm(this.player,this.videoData.Eo,this.videoData.videoId,g.K69(this.videoData),this.videoData.MY,this.videoData.eventId);this.K=Y;g.S(this,this.K);this.K.nB(this.Iq)}};
g.R.unload=function(){this.B&&this.L?wC0(this,!1):(this.W2&&g.qm(this.W2),this.player.l1("captions"),this.fF=[],this.K&&this.K.Il(),this.TZ.clear(),this.nF&&this.player.B_(this.nF),this.Tn());g.Ms.prototype.unload.call(this);this.player.lm();this.player.IH("captionschanged",{})};
g.R.create=function(){this.JT()&&this.load();var Y;a:{var e,K,x;if(this.ai.Z("web_player_nitrate_promo_tooltip")&&((e=this.videoData.getPlayerResponse())==null?0:(K=e.captions)==null?0:(x=K.playerCaptionsTracklistRenderer)==null?0:x.enableTouchCaptionsNitrate)){var z,O;if(e=(Y=this.videoData.getPlayerResponse())==null?void 0:(z=Y.captions)==null?void 0:(O=z.playerCaptionsTracklistRenderer)==null?void 0:O.captionTracks)for(Y=g.a(e),z=Y.next();!z.done;z=Y.next())if(z=z.value,z.kind==="asr"&&z.languageCode===
"en"){Y=!0;break a}}Y=!1}Y&&this.W.publish("showpromotooltip",this.T.element)};
g.R.j1=function(){var Y=RVZ(this.player.getAudioTrack(),g.Uv(this.ai));var e=Y==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?ne(this,this.S):Y==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&du(this)?qK(this):djd(this)||this.S||qs6(this)?ne(this,this.S):du(this)?qK(this):null;if(this.B||this.pF){var K=g.OA(this.K.L,!0);Y=[];for(var x=0;x<K.length;x++){var z=K[x],O=g.ob("TRACK");O.setAttribute("kind","subtitles");O.setAttribute("label",g.Wm(z));O.setAttribute("srclang",g.lp(z));O.setAttribute("id",z.toString());
this.pF||O.setAttribute("src",this.K.N2(z,"vtt"));z===e&&O.setAttribute("default","1");Y.push(O)}e=this.W.uq();e.wA(Y);Y=e.w2();this.bJ&&this.X6.J(Y.textTracks,"change",this.tjd)}else!this.L&&e&&Dj(this,e),this.player.IH("onCaptionsTrackListChanged"),this.player.fX("onApiChange")};
g.R.tjd=function(){for(var Y=this.W.uq().w2().textTracks,e=null,K=0;K<Y.length;K++)if(Y[K].mode==="showing")a:{e=g.OA(this.K.L,!0);for(var x=0;x<e.length;x++)if(e[x].toString()===Y[K].id){e=e[x];break a}e=null}(this.loaded?this.L:null)!==e&&Dj(this,e,!0)};
g.R.ep2=function(){!this.L&&this.B||this.unload()};
g.R.pk=function(Y,e,K,x){if(Y){var z;yLq(this,(z=this.L)!=null?z:void 0);this.K.zN()&&(this.fF=[],this.W.l1("captions"),bP(this.Yq),this.TZ.reset());a:{z=this.TZ;x=x||0;K=jf1(z,Y,K||0);Y=[];try{for(var O=g.a(K),T=O.next();!T.done;T=O.next()){var E=T.value,u=E.trackData,b=E.KH,k=z.ai.Z("safari_live_drm_captions_fix");if(typeof u!=="string"){K=Y;var G=K.concat;if(k&&CC7(u))var B=iOq(z,u,b);else{var L=z,f=e,U=u,h=b,Z=x;if(!mja(U))throw Error("Invalid binary caption track data");L.K||(L.K=new SQ(Z,f));
B=L.K.X(U,h)}var N=G.call(K,B)}else{if(u.substring(0,6)==="WEBVTT")var V=Y.concat(iOq(z,u,b));else{K=Y;var r=K.concat;b:{f=L=void 0;U=z;h=e;if(u[0]==="{")try{U.K||(U.K=new gu(JL1(h)));var H=f=U.K.X(u,b);break b}catch(ec){g.hK(ec);H=[];break b}var I=g.IQ(u);if(!I||!I.firstChild){var w=Error("Invalid caption track data");w.params=u;throw w;}if(I.firstChild.tagName==="timedtext"){if(Number(I.firstChild.getAttribute("format"))===3){U.K||(U.K=new NK(JL1(h),U.ai));H=L=U.K.X(I,b);break b}var $O=Error("Unsupported subtitles format in web player (Format2)");
$O.params=u;throw $O;}if(I.firstChild.tagName==="transcript"){var GM=Error("Unsupported subtitles format in web player (Format1)");GM.params=u;throw GM;}var TM=Error("Invalid caption track data");TM.params=u;throw TM;}V=r.call(K,H)}N=V}Y=N}var F9=Y;break a}catch(ec){z.logger.K(187101178,"Captions parsing failed: "+ec.message+". ");z.clear();F9=[];break a}F9=void 0}e=F9;e.length>0&&(F9=this.L,this.un(F9,!!F9,wu(this)?"g":this.S?"m":"s"));F9=!this.ai.Z("html5_keep_caption_data_after_seek")&&(this.Y===
"LIVE"||this.Y==="SABR_LIVE");this.player.B_(e,void 0,F9);!this.S||this.pF||wu(this)||g.o3(this.ai)||g.FY(this.ai)||g.cQ(this.ai)||this.ai.X6==="shortspage"||this.player.isInline()||(g.qm(this.W2),e=ord({eU:0,N9:5,xH:5,hx:2,textAlign:0,cZ:0,lang:"ko"}),this.g7=[e],F9=["\uc124\uc815\uc744 \ud655\uc778\ud558\ub824\uba74 ","\uc744 \ud074\ub9ad\ud558\uc138\uc694."],this.uJ||(O=new g.K4(g.ae()),g.S(this,O),this.uJ=O.element),O=e.end-e.start,(T=g.Wm(this.L))&&this.g7.push(new Qv(e.start,O,0,e.id,T)),this.g7.push(new Qv(e.start,
O,0,e.id,F9[0]),new Qv(e.start,O,0,e.id,this.uJ,!0),new Qv(e.start,O,0,e.id,F9[1],!0)),this.player.B_(this.g7),g.lL(this.W2));!this.S||this.pF||wu(this)||(g.Uv(this.ai)?yv(this,!0):IU(this,!0),this.C&&(this.C.Y=this.L),this.player.lm());this.S=!1}};
g.R.onCueRangeEnter=function(Y){this.fF.push(Y);bP(this.Yq)};
g.R.onCueRangeExit=function(Y){g.QU(this.fF,Y);this.K instanceof oU&&this.K.T&&this.player.c$([Y]);bP(this.Yq)};
g.R.getCaptionWindowContainerId=function(){return this.T.element.id};
g.R.tIF=function(){en0(this,this.g7);this.g7=null};
g.R.e5=function(){var Y=this;if(!this.x3||!this.B){this.Yq.stop();g.A8c(this.Sd);this.fF.sort(g.lS);var e=this.fF;if(this.nF){var K=g.N4(e,function(O){return this.nF.indexOf(O)===-1},this);
K.length&&(e=K)}e=g.a(e);for(K=e.next();!K.done;K=e.next())Djx(this,K.value);e=g.a(Object.entries(this.LF));var x=e.next();for(K={};!x.done;K={y5:void 0,vk:void 0},x=e.next()){var z=g.a(x.value);x=z.next().value;z=z.next().value;K.y5=x;K.vk=z;this.Sd[K.y5]?(K.vk.element.parentNode||(K.vk instanceof Wa||K.vk instanceof ru||g.Ki(this.LF,function(O){return function(T,E){E!==O.y5&&T.L.params.eU===O.vk.L.params.eU&&T.L.params.N9===O.vk.L.params.N9&&T.L.params.xH===O.vk.L.params.xH&&(T.dispose(),delete Y.LF[E]);
return E===O.y5}}(K),this),this.T.element.appendChild(K.vk.element)),K.vk.N3(this.Sd[K.y5])):(K.vk.dispose(),delete this.LF[K.y5])}}};
g.R.sLZ=function(){Wtd(this,{},!0);this.player.IH("captionssettingschanged")};
g.R.AY=function(){var Y=t2.eI;Y={background:Y.background,backgroundOpacity:Y.backgroundOpacity,charEdgeStyle:Y.charEdgeStyle,color:Y.color,fontFamily:Y.fontFamily,fontSizeIncrement:Y.fontSizeIncrement,fontStyle:Y.bold&&Y.italic?3:Y.bold?1:Y.italic?2:0,textOpacity:Y.textOpacity,windowColor:t2.windowColor,windowOpacity:t2.windowOpacity};var e=NKM()||{};e.background!=null&&(Y.background=e.background);e.backgroundOverride!=null&&(Y.backgroundOverride=e.backgroundOverride);e.backgroundOpacity!=null&&(Y.backgroundOpacity=
e.backgroundOpacity);e.backgroundOpacityOverride!=null&&(Y.backgroundOpacityOverride=e.backgroundOpacityOverride);e.charEdgeStyle!=null&&(Y.charEdgeStyle=e.charEdgeStyle);e.charEdgeStyleOverride!=null&&(Y.charEdgeStyleOverride=e.charEdgeStyleOverride);e.color!=null&&(Y.color=e.color);e.colorOverride!=null&&(Y.colorOverride=e.colorOverride);e.fontFamily!=null&&(Y.fontFamily=e.fontFamily);e.fontFamilyOverride!=null&&(Y.fontFamilyOverride=e.fontFamilyOverride);e.fontSizeIncrement!=null&&(Y.fontSizeIncrement=
e.fontSizeIncrement);e.fontSizeIncrementOverride!=null&&(Y.fontSizeIncrementOverride=e.fontSizeIncrementOverride);e.fontStyle!=null&&(Y.fontStyle=e.fontStyle);e.fontStyleOverride!=null&&(Y.fontStyleOverride=e.fontStyleOverride);e.textOpacity!=null&&(Y.textOpacity=e.textOpacity);e.textOpacityOverride!=null&&(Y.textOpacityOverride=e.textOpacityOverride);e.windowColor!=null&&(Y.windowColor=e.windowColor);e.windowColorOverride!=null&&(Y.windowColorOverride=e.windowColorOverride);e.windowOpacity!=null&&
(Y.windowOpacity=e.windowOpacity);e.windowOpacityOverride!=null&&(Y.windowOpacityOverride=e.windowOpacityOverride);return Y};
g.R.K$=function(Y,e){var K={};Object.assign(K,NKM());Object.assign(K,Y);Wtd(this,K,e);this.player.IH("captionssettingschanged")};
g.R.Tn=function(){!this.B&&this.loaded&&(g.t0(this.LF,function(Y,e){Y.dispose();delete this.LF[e]},this),this.e5())};
g.R.kC=function(Y,e){switch(Y){case "fontSize":if(isNaN(e))break;Y=g.JQ(e,-2,4);this.K$({fontSizeIncrement:Y});return Y;case "reload":e&&!this.B&&Dj(this,this.L,!0);break;case "stickyLoading":e!==void 0&&this.ai.S&&(g.Uv(this.ai)?yv(this,!!e):IU(this,!!e));break;case "track":return Ycq(this,e);case "tracklist":return this.K?g.fh(g.OA(this.K.L,!(!e||!e.includeAsr)),function(K){return g.Hm(K)}):[];
case "translationLanguages":return this.K?this.K.B.map(function(K){return Object.assign({},K)}):[];
case "sampleSubtitles":this.B||e===void 0||KM1(this,!!e);break;case "sampleSubtitlesCustomized":this.B||KM1(this,!!e,e);break;case "recommendedTranslationLanguages":return g.mK();case "defaultTranslationSourceTrackIndices":return this.K?this.K.S:[]}};
g.R.getOptions=function(){var Y="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.ai.S&&Y.push("stickyLoading");return Y};
g.R.YN=function(){var Y=this.L;if(this.W.Jj("captions")){if(this.ai.Z("html5_modify_caption_vss_logging")){var e;return(Y=(e=this.videoData.JH)!=null?e:null)?{cc:g.aNf(Y)}:{}}if(Y)return e=Y.vssId,Y.translationLanguage&&e&&(e="t"+e+"."+g.lp(Y)),{cc:e}}return{}};
g.R.rv6=function(){this.isSubtitlesOn()?(g.Uv(this.ai)?yv(this,!1):IU(this,!1),yLq(this),Dj(this,null,!0)):this.Zr()};
g.R.Zr=function(){var Y=wu(this)||!this.L?ne(this,!0):this.L;Y&&this.z7(Y.vssId,"m");this.isSubtitlesOn()||Dj(this,wu(this)||!this.L?ne(this,!0):this.L,!0)};
g.R.isSubtitlesOn=function(){return!!this.loaded&&!!this.L&&!wu(this)};
g.R.DTq=function(){var Y=wu(this);du(this,Y)?Dj(this,this.getAudioTrack().K,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.ih()&&(this.S=!1,this.L=null,this.K&&(this.K.dispose(),this.K=null)),this.JT()&&(Y?Dj(this,ne(this,!1),!1):this.load()))};
g.R.qZ=function(Y){Y&&(this.xq={top:Y.top,right:Y.right,bottom:Y.bottom,left:Y.left,width:1-Y.left-Y.right,height:1-Y.top-Y.bottom},this.T.element.style.top=this.xq.top*100+"%",this.T.element.style.left=this.xq.left*100+"%",this.T.element.style.width=this.xq.width*100+"%",this.T.element.style.height=this.xq.height*100+"%",this.T.element.style.position="absolute",Y=tSx(this))&&(this.T.element.style.width=Y.width+"px",this.T.element.style.height=Y.height+"px")};
g.R.onVideoDataChange=function(Y,e){Y==="newdata"&&(this.videoData=e,this.loaded&&this.unload(),this.S=!1,this.L=null,this.K&&(this.K.dispose(),this.K=null,this.player.IH("captionschanged",{})),this.JT()&&this.load())};
g.R.getAudioTrack=function(){return this.player.getAudioTrack()};
g.R.g3d=function(){var Y=this.W.uq();Y&&!Y.qT()&&Y.e6();this.W.isFullscreen()?(this.B=this.Vq=!0,this.loaded&&this.j1()):(this.Vq=this.ai.controlsType==="3",this.B=Ssz(this));Dj(this,this.L)};
g.R.S2=function(){var Y,e,K,x=(Y=this.videoData.getPlayerResponse())==null?void 0:(e=Y.captions)==null?void 0:(K=e.playerCaptionsTracklistRenderer)==null?void 0:K.openTranscriptCommand;x&&this.player.O4("innertubeCommand",x)};
g.R.un=function(Y,e,K){var x=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,z="";Y&&(z=Y.vssId,z=z.replace(x,""));var O="";Y&&Y.getId()&&(O=Y.getId()||"");Y&&Y.getXtags()&&(Y=Y.getXtags(),Y=Y.replace(x,""),O=O.concat(";"+Y));this.W.un(e?z:"",e?O:"",K)};
g.R.z7=function(Y,e){Y=(Y||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");Y.length>0&&this.W.z7(Y,e)};g.PA("captions",HOd);})(_yt_player);
